import {esc} from '../summary/helpers.mjs';
// This is a new compact route, not a reconstruction of the earlier example HTML.
export function capitalFlow(lawLink){
 return `<section class="summary-page capital-page capital-route" data-view="kapitaalboom" data-lesson="kapitaalboom" id="kapitaalboom">
<header class="route-heading"><div><p class="summary-kicker">Kies de feiten. Volg de verwerking.</p><h1 tabindex="-1">Kapitaalbelangen in drie stappen</h1></div><button type="button" class="study-button" data-capital-reset>Wis keuzes</button></header>
<p class="route-intro">Drie klikstappen, zonder invulformulier. Je keuzes werken direct door in de volgende stap. Een deelneming, dochtermaatschappij en groepsmaatschappij zijn <strong>afzonderlijke kwalificaties</strong>.</p>
<div class="route-map" role="group" aria-label="Kies een stap"><button type="button" data-capital-stage="classify" aria-pressed="true"><span>1</span><div>Classificatie<small data-route-status="classify">Welke relaties?</small></div></button><b aria-hidden="true">→</b><button type="button" data-capital-stage="value" aria-pressed="false"><span>2</span><div>Waardering<small data-route-status="value">Kies de grondslag</small></div></button><b aria-hidden="true">→</b><button type="button" data-capital-stage="consolidate" aria-pressed="false"><span>3</span><div>Consolidatie<small data-route-status="consolidate">Beoordeel afzonderlijk</small></div></button></div>
<div class="capital-context"><div><span>Wie houdt het belang?</span><div class="route-options" role="group" aria-label="Houder van het belang">${choices('holder',[['legal','Rechtspersoon (bv / nv)'],['partnership','VOF / CV (zonder rechtspersoonlijkheid)'],['person','Natuurlijk persoon']],'legal')}</div></div><div><span>In welke onderneming?</span><div class="route-options" role="group" aria-label="Rechtsvorm van het belang">${choices('target',[['legal','Rechtspersoon (bv / nv)'],['partnership','VOF / CV (zonder rechtspersoonlijkheid)']],'legal')}</div></div><p class="route-form-help"><strong>Wat bedoelen we met VOF / CV?</strong> Een personenvennootschap zonder rechtspersoonlijkheid, bijvoorbeeld een vennootschap onder firma (VOF) of een commanditaire vennootschap (CV). Een bv of nv heet óók een vennootschap, maar valt hier onder <strong>Rechtspersoon</strong>. De houder is degene die het belang bezit; de tweede keuze gaat over de onderneming waarin dat belang wordt gehouden. In deze cursus is de houder doorgaans een bv of nv.</p><p class="study-note-source">Syllabus Deel 1, p. 4–5; ${lawLink('24a','lid 1 en 2')} ${lawLink('24c','lid 1 en 2')}</p><p class="route-scope">De waarderingsroute veronderstelt dat Titel 9 Boek 2 BW op de rapporterende houder van toepassing is. ${lawLink('360')}</p></div>
<div class="route-stage" id="capital-classify"><h2><span class="route-step">1</span> Welke relaties bestaan?</h2><div class="route-classifications" id="capital-qualifications"></div></div>
<div class="route-stage" id="capital-value"><h2><span class="route-step">2</span> Hoe waardeer je enkelvoudig?</h2><div id="capital-value-questions"></div><div class="route-result" id="capital-value-result" role="status" aria-live="polite" aria-atomic="true"></div></div>
<div class="route-stage" id="capital-consolidate"><h2><span class="route-step">3</span> Wat betekent dit voor consolidatie?</h2><div id="capital-consolidation-questions"></div><div class="route-result" id="capital-consolidation-result" role="status" aria-live="polite" aria-atomic="true"></div></div>
<div class="route-step-navigation"><button type="button" class="study-button" data-capital-previous hidden>← Vorige stap</button><button type="button" class="study-button primary" data-capital-next>Verder naar waardering →</button></div>
<p class="route-reading-links"><a href="#waardering">Verdieping waardering →</a><a href="#consolidatieplicht">Verdieping consolidatie →</a><a href="index.html#kap-1">Oefen dit onderwerp →</a></p>
<p class="study-note-source">Bronnen: Syllabus CAFA2 Deel 1, p. 4–19 en 31–36. Artikel, lid en pagina van de aangeleverde wetboekkopie staan bij iedere wettelijke toets. De vragen en uitkomsten zijn uitleg; het wetsvenster toont de letterlijke bron.</p>
<noscript><div class="route-result"><strong>De route zonder scripts</strong><p>Toets deelneming (${lawLink('24c')}), dochter (${lawLink('24a')}) en groep (${lawLink('24b')}) afzonderlijk. Bij een deelneming met invloed van betekenis volgt de vermogensmutatiemethode (${lawLink('389','lid 1')}); bepaal NVW bij voldoende gegevens (lid 2), anders de vermogensmutatiewaarde uit lid 3. Zonder invloed van betekenis beoordeel je verkrijgingsprijs of actuele waarde (${lawLink('384','lid 1')}). Consolidatie wordt afzonderlijk getoetst aan ${lawLink('406','lid 1 en 2')} en de uitzonderingen van ${lawLink('407')} en ${lawLink('408')}.</p></div></noscript></section>`;
}
function choices(field,items,selected){return items.map(([value,label])=>`<button type="button" data-capital-field="${field}" data-capital-value="${value}" aria-pressed="${value===selected}">${esc(label)}</button>`).join('');}
