/* Chapter orientation and exam-specific study routes, derived from supplied CAFA2 material. */
import {esc} from '../summary/helpers.mjs';
import {renderExamApproach} from './exam-approach.mjs';

export const orientation = {
 'kapitaalbelangen': {
  need:["Je weet dat een aandeel een belang in het eigen vermogen van een onderneming vertegenwoordigt en dat een aandeelhouder niet hetzelfde is als een schuldeiser.", "Je kunt activa, schulden en eigen vermogen op een balans onderscheiden, en weet dat de winst-en-verliesrekening het resultaat over een periode weergeeft.", "Je kunt een percentage en een verhouding berekenen. De juridische verschillen tussen deelneming, dochter en groep leer je in dit hoofdstuk; die hoef je vooraf nog niet te kennen."],
  learn:['<a href="#kwalificatie">Deelneming en belegging</a>, <a href="#dochter">dochtermaatschappij</a> en <a href="#consolidatieplicht">groepsverband</a> afzonderlijk beoordelen.','Van invloed van betekenis naar de passende <a href="#waardering">waarderingsgrondslag</a> redeneren.'],
  source:'Syllabus Deel 1, p. 4–19; art. 2:24a–24d en 2:389 BW.'
 },
 'verwerking-kapitaalbelangen': {
  need:["Je kunt een journaalpost met debet en credit opstellen en het verschil uitleggen tussen een balansrekening en een resultaatrekening.", "Je weet waarom ontvangst niet hetzelfde is als opbrengst: een betaling kan ook een bestaande vordering afwikkelen. Ook kun je een balansverloop maken: beginstand plus mutaties is eindstand.", "Je begrijpt uit <a href=\"#kapitaalbelangen\">hoofdstuk 1</a> het verschil tussen verkrijgingsprijs en nettovermogenswaarde. Je beheerst de basis van afschrijven en bruto/netto rekenen."],
  learn:['De aankoop uitsplitsen in <a href="#fair-value">grondslagverschillen</a> en <a href="#goodwill">goodwill</a>.','De deelnemingswaarde laten aansluiten via <a href="#resultaat-deelneming">resultaat</a>, <a href="#dividend">dividend</a> en overige mutaties.','<a href="#wettelijke-reserve">Wettelijke reserves</a>, eigen aandelen en een <a href="#stelselwijziging">stelselwijziging</a> verwerken.'],
  source:'Syllabus Deel 1, p. 15–30; art. 2:389 leden 2–3 en 6–7 BW.'
 },
 'vreemde-valuta': {
  need:["Je kunt een balans en winst-en-verliesrekening lezen en het verschil uitleggen tussen bezit, een geldvordering en een geldschuld.", "Je kunt met verhoudingen rekenen en een koersnotatie lezen: bij € 0,90 per USD is USD 100 gelijk aan € 90. Staat de koers andersom, dan draai je de berekening om.", "Je beheerst de basis van FIFO, kostprijs van de omzet en afschrijving. Voor de boeking bij de moeder kun je het <a href=\"#verwerking-kapitaalbelangen\">verloop van een deelneming</a> uit hoofdstuk 2 volgen."],
  learn:['<a href="#valuta">Lokale, functionele en presentatievaluta</a> onderscheiden en daaruit de methode afleiden.','Koersen toewijzen aan <a href="#tijdstipmethode">monetaire en niet-monetaire posten</a>, voorraadlagen en waardeverminderingen.','Het verschil tussen <a href="#monetaire-positie">koersresultaat</a> en <a href="#omrekenreserve">omrekeningsreserve</a> verklaren en narekenen.'],
  source:'Syllabus Deel 2, §2–4, p. 4–9; art. 2:384 lid 5 en 2:389 lid 8 BW.'
 },
 'consolidatieproces': {
  need:["Je kunt twee afzonderlijke balansen en winst-en-verliesrekeningen lezen en gelijksoortige posten bij elkaar optellen.", "Je begrijpt dat een vordering bij de ene onderneming een schuld bij de andere kan zijn, en dat dezelfde interne transactie in beide administraties voorkomt.", "Je kent de <a href=\"#kapitaalbelangen\">begrippen deelneming, dochter en groep</a> uit hoofdstuk 1. Consolidatieboekingen zelf zijn nog geen vereiste; die bouw je hier op."],
  learn:['De <a href="#consolidatieplicht">consolidatieplicht en consolidatiekring</a> met de wet onderbouwen.','Begrijpen waarom je eerst gelijksoortige cijfers samenvoegt en vervolgens <a href="#onderlinge-posten">onderlinge verhoudingen elimineert</a>.','<a href="#streams">Downstream, upstream en sidestream</a> herkennen vóór je een correctie berekent.'],
  source:'Syllabus Deel 1, p. 31–37; Deel 3, p. 5–7; art. 2:405–409 BW.'
 },
 'consolidatie-nettovermogenswaarde': {
  need:["Je kunt de <a href=\"#resultaat-deelneming\">enkelvoudige NVW-boekingen</a> voor resultaat en dividend uitleggen en weet wat daarvan al in de cijfers van de moeder is verwerkt.", "Je begrijpt het <a href=\"#proces\">consolidatieproces</a> en het verschil tussen een correctie in de administratie van de moeder en een eliminatie op het consolidatiewerkblad.", "Je kunt winst in een voorraad berekenen en een eindstand van een jaarmutatie onderscheiden. Je weet dat een marge op verkoopprijs iets anders is dan een opslag op kostprijs."],
  learn:['De <a href="#voorraadtabel">voorraadtabel</a> gebruiken om de totale IC-winst en de verschillende correcties te scheiden.','De <a href="#downstream-nvw">downstream-</a> en <a href="#upstream-nvw">upstreamcorrectie</a> enkelvoudig én geconsolideerd verwerken.','Eindstanden voor de balans onderscheiden van mutaties voor het resultaat en dubbeltelling voorkomen.'],
  source:'Syllabus Deel 3, §3–4, p. 8–103; art. 2:384 lid 2, 2:389 en 2:405 BW.'
 },
 'consolidatie-verkrijgingsprijs': {
  need:["Je weet bij <a href=\"#waardering\">verkrijgingsprijs</a> wat er wel en niet met de boekwaarde gebeurt en hoe regulier dividend in de enkelvoudige jaarrekening wordt verwerkt.", "Je begrijpt het <a href=\"#consolidatieproces\">consolidatieproces</a>, de begrippen eigen vermogen en resultaat en het onderscheid tussen het aandeel van de moeder en dat van derden.", "Je kunt een afschrijving, een voorraadwinst en een mutatie tussen twee balansdata berekenen. NVW-boekingen mag je niet automatisch overnemen; het verschil wordt hier uitgelegd."],
  learn:['Verklaren waarom de correcties bij <a href="#consolidatie-hk">verkrijgingsprijs</a> anders over de werkbladen zijn verdeeld dan bij NVW.','Deelneming, derdenbelang, goodwill, dividend en <a href="#upstream-hk">IC-resultaten</a> in de consolidatie verwerken.','Het groepsresultaat laten aansluiten op het <a href="#resultaataansluiting">meerderheidsresultaat en het resultaat derden</a>.'],
  source:'Syllabus Deel 3, §5–6, p. 104–185; art. 2:405, 2:411 lid 2 en 2:413 BW.'
 },
 'bijzondere-consolidatie': {
  need:["Je kunt de basisboekingen voor <a href=\"#consolidatie-nettovermogenswaarde\">NVW-consolidatie</a> en <a href=\"#consolidatie-verkrijgingsprijs\">consolidatie bij verkrijgingsprijs</a> volgen en weet in welke jaarrekening elke boeking thuishoort.", "Je begrijpt dat interne winst pas gerealiseerd is wanneer de groep tegenover derden presteert en dat voorraadwinst op een balansdatum iets anders is dan de resultaatmutatie in een jaar.", "Je kunt afzonderlijke aandelen van moeder en derden berekenen en de boekwaarde en jaarlijkse afschrijving van een materieel vast actief bepalen."],
  learn:['<a href="#proportioneel">Proportionele consolidatie</a> onderscheiden van integrale consolidatie.','Bij <a href="#sidestream">sidestream</a> toenemend en afnemend belang uit elkaar houden.','IC-winst op <a href="#mva">materiële vaste activa</a> en de latere realisatie via afschrijving volgen.'],
  source:'Syllabus Deel 3, §7–8, p. 186–248; art. 2:409 BW.'
 }
};
export function orientationHtml(id) {
 const o=orientation[id]; if(!o)throw Error('Geen hoofdstukoriëntatie: '+id);
 return '<div class="chapter-orientation"><section><h2>Dit heb je nodig</h2><p class="orientation-caption">Voorkennis: dit begrijp je al vóór je begint.</p><ul>'+o.need.map(t=>'<li>'+t+'</li>').join('')+'</ul></section><section><h2>Dit ga je leren</h2><ul>'+o.learn.map(t=>'<li>'+t+'</li>').join('')+'</ul></section><p class="study-note-source">Voorkennis afgeleid uit het ingangsniveau (Onderwijsprogramma 2026, §2, p. 3) en de opbouw van de leerstof. Leerdoelen: '+esc(o.source)+'</p></div>';
}

export const examRoutes=[
 {id:'stemrecht',topic:'kap',label:'Kapitaalbelangen',title:'Niet één percentage, maar het juiste recht',exam:'cafa2-20250924',date:'24 september 2025',questions:'7 en 8a',pages:'4',
  task:'Vraag 7 vraagt met de wet te motiveren of Bosa een dochtermaatschappij is. Vraag 8a vraagt vervolgens om de dividendboeking bij NVW.',
  steps:[['Lees het gevraagde recht.','De dochtertoets draait hier om stemmen. Het model noemt 55% geplaatst kapitaal, maar berekent het stemrecht afzonderlijk: 380 ÷ 700 = 54,3%.'],['Pas de norm toe.','Het model werkt expliciet met Norm, Motivering en Conclusie. Meer dan de helft van de stemmen leidt in deze casus tot een dochtermaatschappij (art. 2:24a lid 1 onder a BW).'],['Bereken het dividend met het winstrecht.','Vraag 8a gebruikt 480 ÷ 1.000 = 48%. Het dividend is dus 48% × € 100.000 = € 48.000; bij NVW boekt het model Bank/Te vorderen dividend aan Deelneming Bosa.']],
  check:'Controleer welke noemer bij het gevraagde recht hoort. 55% kapitaal, 54,3% stemmen en 48% winstrecht zijn in dezelfde casus verschillende gegevens.',lesson:'flex-aandelen'},
 {id:'stelsel',topic:'kap',label:'Kapitaalbelangen',title:'Stelselwijziging: houd de aankooplagen uit elkaar',exam:'cafa2-20240930',date:'30 september 2024',questions:'3 en 4',pages:'4',
  task:'Het antwoordmodel verwerkt de overgang naar waardering tegen zichtbaar eigen vermogen en berekent daarna de totale boekwaarde van de deelneming.',
  steps:[['Scheid het eerder gekochte en het later gekochte belang.','Voor het 35%-belang stijgt de boekwaarde van € 400.000 naar 35% × € 1.600.000 = € 560.000. Het verschil van € 160.000 wordt in het model aan Overige reserves toegevoegd.'],['Zonder de goodwill uit de latere aankoop af.','Bij de 25%-aankoop is de goodwill € 275.000. Na € 27.500 afschrijving resteert € 247.500. De waarde zonder goodwill stijgt van € 350.000 naar € 400.000. Het model boekt daarom € 22.500 naar Overige reserves: € 50.000 vermogenssprong minus € 27.500 afschrijving. Deelneming neemt per saldo € 225.000 af.'],['Sluit de eindwaarde onafhankelijk aan.','Vraag 4 controleert de totale deelneming op 60% × € 1.600.000 = € 960.000. De boekwaardebrug geeft hetzelfde: € 400.000 + € 160.000 + € 625.000 − € 225.000.']],
  check:'Een gemiddeld aankoopbedrag verhult hier welke goodwill en vermogensaanpassing bij welke aankooplaag hoort.',lesson:'stelselwijziging'},
 {id:'monetair',topic:'val',label:'Vreemde valuta',title:'Tijdstipmethode: bouw de monetaire positie op',exam:'cafa2-20250417',date:'17 april 2025',questions:'11',pages:'8',
  task:'Vraag 11 verlangt een gespecificeerde berekening van het koersverschil en vraagt expliciet of het resultaat positief of negatief is.',
  steps:[['Bepaal de monetaire beginpositie.','Het model telt debiteuren en liquide middelen op en trekt lening en crediteuren af: USD −1.192.000. Tegen 0,87 is dat € −1.037.040.'],['Verwerk de mutaties tegen de bijbehorende koersen.','De tabel verwerkt onder meer inkopen, verkopen, kosten, rente, desinvestering en afwaardering. De monetaire positie komt theoretisch uit op USD −115.000 en € −30.550.'],['Vergelijk met de werkelijke eindpositie tegen slotkoers.','USD −115.000 × 0,97 = € −111.550. Het verschil met € −30.550 bedraagt € −81.000: het model neemt dit op als koersverlies in de winst-en-verliesrekening.']],
  check:'Het koersverschil volgt uit twee waarderingen van dezelfde monetaire eindpositie. Alleen de gehele balans tegen slotkoers omrekenen levert deze specificatie niet op.',lesson:'monetaire-positie'},
 {id:'slotkoers',topic:'val',label:'Vreemde valuta',title:'Slotkoersmethode: scheid resultaat en reserve',exam:'cafa2-20250417',date:'17 april 2025',questions:'13 en 14',pages:'9',
  task:'Vraag 13 vraagt het deelnemingsverloop en een gespecificeerd omrekeningsverschil. Vraag 14 vraagt de bijbehorende journaalposten.',
  steps:[['Zet de vermogensbrug neer.','Beginvermogen: USD 2.000.000 × 0,87 = € 1.740.000. Resultaat: USD 400.000 × 0,93 = € 372.000. De voorlopige eindwaarde is € 2.112.000.'],['Specificeer het omrekeningsverschil.','Op het beginvermogen: USD 2.000.000 × (0,97 − 0,87) = € 200.000. Op het resultaat: USD 400.000 × (0,97 − 0,93) = € 16.000. Samen: € 216.000.'],['Laat de journaalpost aansluiten.','De eindwaarde wordt € 2.328.000. Het model boekt Deelneming Glacier debet € 588.000, aan Resultaat deelneming € 372.000 en aan Reserve omrekeningsverschillen € 216.000.']],
  check:'Het verschil van € 216.000 hoort in deze uitwerking bij de omrekeningsreserve, niet bij het resultaat uit de monetaire-positiebrug van vraag 11.',lesson:'omrekenreserve'},
 {id:'nvw',topic:'nvw',label:'NVW-consolidatie',title:'Voorraadtabel: eindstand is niet de jaarmutatie',exam:'cafa2-20240422',date:'22 april 2024',questions:'16, 17 en 19',pages:'10–11',
  task:'Vraag 16 vraagt de sidestreamvoorraadtabel, vraag 17 de intracomptabele correctie en vraag 19 de balanseliminaties.',
  steps:[['Vul begin én einde in en bepaal de mutatie.','Het model geeft € 25.000 IC-winst in de beginvoorraad en € 75.000 in de eindvoorraad. De interne correctiekolom is 70%: € 17.500 en € 52.500. De toename is € 35.000.'],['Gebruik de mutatie voor de interne jaarboeking.','Vraag 17 gebruikt € 35.000 × 80% = € 28.000 na 20% belasting. Het model boekt Resultaat uit deelnemingen aan Deelneming Adoorn. Dit is een enkelvoudige boeking bij de moeder.'],['Gebruik de eindstand voor de geconsolideerde balans.','Vraag 19 elimineert de volledige € 75.000 eindvoorraadwinst. Daarbinnen is € 52.500 de interne correctie, gesplitst in € 42.000 Deelneming en € 10.500 belastingvoorziening; derden en aanvullend resultaat worden apart verwerkt.']],
  check:'Bij vraag 17 gaat het om € 35.000 mutatie vóór belasting; bij de deelnemingscomponent in vraag 19 om € 52.500 eindstand vóór belasting. Dat verschil wordt door de gevraagde werklaag en datum veroorzaakt.',lesson:'sidestream-ab'},
 {id:'hk',topic:'hk',label:'HK-consolidatie',title:'Bij HK is de interne-correctiekolom hier leeg',exam:'cafa2-20240422',date:'22 april 2024',questions:'22',pages:'13',
  task:'Vraag 22 vraagt de voorraadtabel voor de upstreamleveringen van Armweide aan Nolde bij waardering tegen verkrijgingsprijs.',
  steps:[['Bereken eerst de volledige ongerealiseerde winst.','Het model geeft € 27.000 in de beginvoorraad en € 42.000 in de eindvoorraad. De toename is € 15.000.'],['Neem geen NVW-correctie over in de enkelvoudige cijfers.','De kolom Interne correctie bij N blijft in dit HK-antwoordmodel leeg. De IC-correctie wordt in de consolidatie verdeeld.'],['Verdeel over derden en geconsolideerd resultaat.','Derden krijgen 20%: € 5.400 begin, € 8.400 einde en € 3.000 toename. De overige 80% is respectievelijk € 21.600, € 33.600 en € 12.000.']],
  check:'De lege kolom is niet een ontbrekend antwoord. De gekozen enkelvoudige grondslag bepaalt welke correctie al in de eigen administratie thuishoort.',lesson:'upstream-hk'},
 {id:'dividend-hk',topic:'hk',label:'HK-consolidatie',title:'Ontvangen dividend: lees de aankoopgegevens mee',exam:'cafa2-20240422',date:'22 april 2024',questions:'20 en 21',pages:'13',
  task:'Vraag 20 verwerkt de verwerving van het 25%-belang. Vraag 21 vraagt vervolgens de boeking van de winstverdeling over 2022.',
  steps:[['Koppel de uitkering aan de aanschafgegevens.','Vraag 20 boekt de deelneming voor € 2.650.000. Vraag 21 verwerkt niet de volledige ontvangst van € 160.000 als opbrengst.'],['Volg de splitsing in het model.','Het model vermindert Deelneming Armweide met 25% × € 200.000 = € 50.000 en verantwoordt het restant van € 110.000 als Dividendopbrengst.'],['Controleer de ontvangst tegen beide tegenrekeningen.','Bank € 160.000 = Deelneming € 50.000 + Dividendopbrengst € 110.000. De kwalificatie van een uitkering vraagt dus meer dan alleen de naam van de waarderingsmethode.']],
  check:'Het leeradvies is de aankoopvoorwaarden naast de dividendvraag te leggen. De exacte modelbedragen zijn geen algemene formule voor ieder HK-dividend.',lesson:'dividend'}
];
export function examRoutePage(){ return renderExamApproach(examRoutes); }
