import fs from 'node:fs';
import {esc} from '../summary/helpers.mjs';
export const guides=JSON.parse(fs.readFileSync(new URL('./guide.json',import.meta.url),'utf8'));
export const laws=JSON.parse(fs.readFileSync(new URL('./laws.json',import.meta.url),'utf8'));
export const examNotes=JSON.parse(fs.readFileSync(new URL('./exam-notes.json',import.meta.url),'utf8'));
export const lawLink=(a,p='',base='')=>'<a class="law-ref" data-law="'+esc(a)+'" data-law-part="'+esc(p)+'" href="'+base+'#wet-'+esc(a)+'">art. 2:'+esc(a)+(p?' '+esc(p):'')+' BW<span>p. '+esc(laws[a]?.pages||laws[a]?.page||'onbekend')+'</span></a>';
export const lawRail=(rs,base='')=>'<div class="law-rail" aria-label="Wetsartikelen bij deze uitleg">'+rs.map(r=>lawLink(r.article,r.part,base)).join(' ')+'</div>';
export function topicAddition(id){const g=guides[id];if(!g)return '';return '<p class="study-principle">'+esc(g.why)+' '+esc(g.practice)+'</p>'+lawRail(g.refs);}
export function noteHtml(id,custom='',base='samenvatting.html',source=''){
 const g=guides[id];if(!g)return '';
 return '<div class="study-answer-note"><p class="study-note-caption">Aanvullende toelichting bij het antwoord</p><p>'+esc(custom||g.method)+'</p><p>'+esc(g.why)+' '+esc(g.practice)+'</p>'+lawRail(g.refs,base)+'<p class="study-note-source">'+(source?'Uitwerking bij '+esc(source)+'. ':'')+'Didactische toelichting bij het model en de syllabus; de wetsartikelen geven het wettelijke kader. <a href="'+base+'#'+id+'">Bijbehorende uitleg in de samenvatting →</a></p></div>';
}
export function lawPage(){return '<section class="summary-page" data-view="wetsartikelen" data-lesson="wetsartikelen" id="wetsartikelen"><p class="summary-kicker">Je studie-wetboek</p><h1 tabindex="-1">Wetsartikelen bij CAFA2</h1><p>Zoek het criterium in het wetboek, verbind het aan de feiten en trek dan de conclusie. De gekleurde artikelverwijzingen openen de tekst zonder je plaats in de vraag of samenvatting te verlaten.</p><p class="study-note-source">Tekst uit de aangeleverde kopie <strong>Burgerlijk wetboek Boek 2.pdf</strong>, met versievermelding 01-01-2025, art. 24a t/m 24d en 360 t/m 414. Dit is de studieversie, geen vervanging door een later geraadpleegde wettekst. De korte artikeltitels hieronder zijn leeslabels; de tekst eronder is de bronweergave.</p><div class="law-quick">'+['24a','24b','24c','24d','384','385','386','389','405','406','407','408','409'].map(a=>lawLink(a)).join(' ')+'</div><label class="study-law-search">Zoek artikel, lid of woord<input type="search" id="study-law-search" placeholder="Bijvoorbeeld 389, goodwill of groepsdeel"></label><p id="law-search-count" aria-live="polite"></p><div class="law-directory">'+Object.entries(laws).sort(([a],[b])=>parseInt(a)-parseInt(b)||a.localeCompare(b)).map(([a,l])=>'<details class="law-article" id="wet-'+a+'" data-law-entry="'+a+'"><summary><span class="law-label">Art. 2:'+a+' BW</span><span>'+esc(l.title)+'</span></summary><div class="law-verbatim"><p class="study-note-source">Studiekopie, p. '+(l.pages||l.page)+'.</p>'+l.paragraphs.map(s=>'<p>'+esc(s)+'</p>').join('')+'</div></details>').join('')+'</div><p>Bij vreemde valuta en intercompanyboekingen geeft het BW vaak het algemene kader. De concrete omrekenregels, percentages en journaalpostmethodiek komen uit de CAFA2-syllabus en de uitwerkingen. Een artikelnummer vervangt die uitwerking niet.</p>'+lawLink('393','lid 3')+' '+lawLink('362','lid 1')+'</section>';}
export {capitalFlow} from './capital-flow.mjs';
