import fs from 'node:fs';
import {esc} from '../summary/helpers.mjs';
export const guides=JSON.parse(fs.readFileSync(new URL('./guide.json',import.meta.url),'utf8'));
export const laws=JSON.parse(fs.readFileSync(new URL('./laws.json',import.meta.url),'utf8'));
export const examNotes=JSON.parse(fs.readFileSync(new URL('./exam-notes.json',import.meta.url),'utf8'));
export const lawLink=(a,p='',base='')=>'<a class="law-ref" data-law="'+esc(a)+'" data-law-part="'+esc(p)+'" href="'+base+'#wet-'+esc(a)+'">art. 2:'+esc(a)+(p?' '+esc(p):'')+' BW<span>p. '+esc(laws[a]?.pages||laws[a]?.page||'onbekend')+'</span></a>';
export const lawRail=(rs,base='')=>'<div class="law-rail" aria-label="Wetsartikelen bij deze uitleg">'+rs.map(r=>lawLink(r.article,r.part,base)).join(' ')+'</div>';
export function topicAddition(id){const g=guides[id];if(!g)return '';return '<p class="study-principle">'+esc(g.why)+' '+esc(g.practice)+'</p>'+lawRail(g.refs);}
export function noteHtml(id,custom='',base='samenvatting.html',source=''){
 const g=guides[id];if(!g)return '';
 return '<div class="study-answer-note"><p class="study-note-caption">Aanvullende toelichting bij het antwoord</p><p>'+esc(custom||g.method)+'</p><p>'+esc(g.why)+' '+esc(g.practice)+'</p>'+lawRail(g.refs,base)+'<p class="study-note-source">'+(source?'Uitwerking bij '+esc(source)+'. ':'')+'Didactische toelichting bij het model en de syllabus; de wetsartikelen geven het wettelijke kader. <a href="'+base+'#'+id+'">Bijbehorende uitleg in de samenvatting →</a></p></div>';
}
export function lawPage(){return '<section class="summary-page" data-view="wetsartikelen" data-lesson="wetsartikelen" id="wetsartikelen"><p class="summary-kicker">Je studie-wetboek</p><h1 tabindex="-1">Wetsartikelen bij CAFA2</h1><p>Zoek het criterium in het wetboek, verbind het aan de feiten en trek dan de conclusie. De gekleurde artikelverwijzingen openen de tekst zonder je plaats in de vraag of samenvatting te verlaten.</p><p class="study-note-source">Tekst uit de aangeleverde kopie <strong>Burgerlijk wetboek Boek 2.pdf</strong>, met versievermelding 01-01-2025, art. 24a t/m 24d en 360 t/m 414. Dit is de studieversie, geen vervanging door een later geraadpleegde wettekst. De korte artikeltitels hieronder zijn leeslabels; de tekst eronder is de bronweergave.</p><div class="law-quick">'+['24a','24b','24c','24d','384','385','386','389','405','406','407','408','409'].map(a=>lawLink(a)).join(' ')+'</div><label class="study-law-search">Zoek artikel, lid of woord<input type="search" id="study-law-search" placeholder="Bijvoorbeeld 389, goodwill of groepsdeel"></label><p id="law-search-count" aria-live="polite"></p><div class="law-directory">'+Object.entries(laws).sort(([a],[b])=>parseInt(a)-parseInt(b)||a.localeCompare(b)).map(([a,l])=>'<details class="law-article" id="wet-'+a+'" data-law-entry="'+a+'"><summary><span class="law-label">Art. 2:'+a+' BW</span><span>'+esc(l.title)+'</span></summary><div class="law-verbatim"><p class="study-note-source">Studiekopie, p. '+(l.pages||l.page)+'.</p>'+l.paragraphs.map(s=>'<p>'+esc(s)+'</p>').join('')+'</div></details>').join('')+'</div><p>Bij vreemde valuta en intercompanyboekingen geeft het BW vaak het algemene kader. De concrete omrekenregels, percentages en journaalpostmethodiek komen uit de CAFA2-syllabus en de uitwerkingen. Een artikelnummer vervangt die uitwerking niet.</p>'+lawLink('393','lid 3')+' '+lawLink('362','lid 1')+'</section>';}
const arrow=t=>'<div class="capital-arrow"><span aria-hidden="true">↓</span> '+t+'</div>';
const box=(title,text,refs=[],cls='')=>'<div class="capital-node '+cls+'"><strong>'+title+'</strong><p>'+text+'</p>'+lawRail(refs.map(([article,part])=>({article,part})))+'</div>';
export function flowPage(){return `<section class="summary-page capital-page" data-view="kapitaalboom" data-lesson="kapitaalboom" id="kapitaalboom">
<p class="summary-kicker">Van juridische relatie naar jaarrekening</p><h1 tabindex="-1">Beslisboom kapitaalbelangen</h1>
<p>Volg de pijlen, maar beoordeel deelneming, dochtermaatschappij en groepsmaatschappij <strong>naast elkaar</strong>. Dezelfde maatschappij kan meer dan één kwalificatie hebben. Kies daarna de enkelvoudige waardering en beoordeel afzonderlijk de consolidatie.</p>
<nav class="capital-stages" aria-label="Stappen in de beslisboom"><a href="#capital-classify">1 · Classificatie</a><a href="#capital-value">2 · Waardering</a><a href="#capital-consolidate">3 · Consolidatie</a></nav>
<div id="capital-classify" class="capital-stage"><h2>1. Welke relaties bestaan?</h2>
${box('Start: wie houdt het belang, en in wie?','Maak onderscheid tussen een rechtspersoon, een vennootschap en een natuurlijke persoon. Artikel 2:24a noemt een rechtspersoon als moeder; artikel 2:24c maakt onderscheid tussen deelneming in een rechtspersoon (lid 1) en in een vennootschap (lid 2). Een natuurlijke persoon valt niet als houder onder deze wettelijke deelnemings- en dochterdefinities. Beoordeel het toepasselijke verslaggevingsstelsel afzonderlijk.',[['24c','lid 1 en 2'],['24a','lid 1 en 2'],['360','']])}
${arrow('Drie parallelle toetsen, dus niet stoppen na de eerste “ja”.')}
<div class="capital-parallel">
<article class="capital-lane lane-deel"><p class="capital-lane-label">A · Doel van het belang</p><h3>Deelneming?</h3><div class="capital-question"><p><strong>In een rechtspersoon:</strong> kapitaal voor eigen rekening, met duurzame verbondenheid ten dienste van de eigen werkzaamheid?</p>${lawLink('24c','lid 1')}<p class="capital-presumption">Vanaf 20% <strong>geplaatst kapitaal</strong>: vermoeden van deelneming. Minder dan 20% sluit een deelneming niet uit.</p></div><details><summary>In een vennootschap, zoals een VOF?</summary><p>Voor een rechtspersoon: is hij of zijn dochter volledig aansprakelijke vennoot, of anderszins vennoot met duurzame verbondenheid ten dienste van de eigen werkzaamheid?</p>${lawLink('24c','lid 2')}</details><div class="capital-branches"><div class="capital-outcome is-yes"><b>Ja → Deelneming</b><p>Ga voor de waardering naar stap 2.</p></div><div class="capital-outcome is-no"><b>Nee → Geen deelneming</b><p>Bij een gehouden kapitaalbelang beoordeel je de belegging en haar bestemming.</p></div></div></article>
<article class="capital-lane lane-dochter"><p class="capital-lane-label">B · Uitoefenbare bevoegdheden</p><h3>Dochtermaatschappij?</h3><div class="capital-question"><p><strong>Meer dan 50% stemmen</strong> uitoefenbaar, alleen of samen met dochters, eventueel door een overeenkomst?</p>${lawLink('24a','lid 1 onder a')}<p><strong>Of:</strong> lid/aandeelhouder én meer dan de helft van bestuurders of commissarissen kunnen benoemen of ontslaan?</p>${lawLink('24a','lid 1 onder b')}</div><details><summary>Gelijkstelling en toerekening</summary><p>Een onder eigen naam optredende vennootschap waarin de rechtspersoon of zijn dochter als vennoot volledig aansprakelijk is, wordt gelijkgesteld. Beoordeel ook de rechten op aandelen voor rekening van anderen en verpande aandelen volgens de specifieke voorwaarden.</p>${lawLink('24a','lid 2, 3 en 4')} ${lawLink('24d')}</details><div class="capital-branches"><div class="capital-outcome is-yes"><b>Ja → Dochtermaatschappij</b><p>Toets deelneming en groep nog steeds afzonderlijk.</p></div><div class="capital-outcome is-no"><b>Nee → Geen dochter op deze gronden</b><p>Deelneming of groepsmaatschappij kan nog wel van toepassing zijn.</p></div></div></article>
<article class="capital-lane lane-groep"><p class="capital-lane-label">C · Economische samenhang</p><h3>Groepsmaatschappij?</h3><div class="capital-question"><p><strong>Economische eenheid</strong> waarin rechtspersonen en vennootschappen <strong>organisatorisch verbonden</strong> zijn?</p>${lawLink('24b')}<p>Onderzoek de centrale leiding en samenhang van de activiteiten zoals de syllabus dit uitwerkt. Een dochterrelatie is niet automatisch voldoende.</p></div><details><summary>Waarom een afzonderlijke toets?</summary><p>Juridische zeggenschap en feitelijk groepsverband beantwoorden verschillende vragen. Ook zonder kapitaalbelang kan groepsverband relevant zijn. De wet spreekt bij de consolidatiekring bovendien over dochtermaatschappijen <em>in de groep</em> en andere onder overheersende zeggenschap of centrale leiding staande rechtspersonen.</p>${lawLink('406','lid 1 en 2')}</details><div class="capital-branches"><div class="capital-outcome is-yes"><b>Ja → Groepsmaatschappij</b><p>Ga daarnaast naar stap 3: consolidatieplicht en kring.</p></div><div class="capital-outcome is-no"><b>Nee → Geen groepsverband vastgesteld</b><p>Dit is nog geen volledige conclusie over iedere mogelijke consolidatiegrond.</p></div></div></article>
</div><p class="capital-bridge">Deze toetsen voorkomen dat het woord “dochter” ten onrechte tegelijk als antwoord op classificatie, waardering en consolidatie wordt gebruikt.</p></div>
<div id="capital-value" class="capital-stage"><h2>2. Hoe wordt het belang enkelvoudig gewaardeerd?</h2>
${box('Deelneming én invloed van betekenis?','Beoordeel de invloed op het zakelijke en financiële beleid. Vanaf 20% van de naar eigen inzicht uit te brengen stemmen wordt die invloed vermoed. Dit zijn stemmen, niet het geplaatste kapitaal uit de deelnemingstoets. De omstandigheden kunnen het vermoeden ondersteunen of weerleggen.',[['389','lid 1']],'capital-decision')}
<div class="capital-value-grid"><div><p class="capital-path-label is-yes">Ja ↓ Vermogensmutatiemethode</p>
${box('Voldoende gegevens voor NVW?','Activa, voorzieningen, schulden en resultaat op dezelfde grondslagen bepalen als bij de moeder.',[['389','lid 2']])}
<div class="capital-branches"><div class="capital-outcome is-yes"><b>Ja → Nettovermogenswaarde</b><p>Aandeel in het herrekende nettovermogen. Mutaties volgen resultaat, dividend en rechtstreekse vermogenswijzigingen.</p>${lawLink('389','lid 2')}</div><div class="capital-outcome is-no"><b>Onvoldoende gegevens → Andere vermogensmutatiewaarde</b><p>Volgens Titel 9 bepaalde waarde, daarna wijzigen met aandeel in resultaat en uitkeringen. In de syllabus: zichtbaar eigen vermogen. Dit is geen automatische terugval op onveranderlijke kostprijs.</p>${lawLink('389','lid 3')}</div></div>
<details class="capital-exception"><summary>Uitzondering: gegronde reden om af te wijken</summary><p>Artikel 2:389 lid 9 staat afwijking van lid 1 toe wegens in de toelichting te vermelden gegronde redenen. Dit is een afzonderlijke uitzondering, niet hetzelfde als onvoldoende gegevens in lid 3. Motiveer daarna ook de gekozen alternatieve grondslag.</p>${lawLink('389','lid 9')} ${lawLink('384','lid 1')}</details>
</div><div><p class="capital-path-label is-no">Nee ↓ Geen toepassing van de hoofdregel van 389 lid 1</p>
${box('Verkrijgingsprijs of actuele waarde','Bij een deelneming zonder invloed van betekenis of een belegging verwijst de syllabus naar artikel 2:384. Deze mogelijkheden zijn geen onbeperkte keuze naast de NVW-plicht; beoordeel steeds het inzicht en de toepasselijke voorwaarden.',[['384','lid 1 en 4']])}
<details open><summary>Verkrijgingsprijs</summary><p>Inkoopprijs plus bijkomende kosten. Beoordeel vervolgens waardeverminderingen. Voor vaste activa wordt een naar verwachting duurzame waardevermindering verwerkt; financiële vaste activa kennen daarnaast de mogelijkheid uit de tweede zin van lid 3.</p>${lawLink('388','lid 1')} ${lawLink('387','lid 2, 3 en 4')}</details>
<details open><summary>Actuele waarde</summary><p>Beoordeel resultaatverwerking en eventuele herwaarderingsreserve samen. Een waardestijging gaat niet in alle gevallen uitsluitend naar de reserve: artikel 2:384 lid 7 en artikel 2:390 bevatten uitzonderingen en voorwaarden, waaronder frequente marktnoteringen.</p>${lawLink('384','lid 7')} ${lawLink('390','lid 1 en 3')}</details>
</div></div>
<div class="capital-followups"><details><summary>Goodwill en wettelijke reserve</summary><p>Bij eerste vermogensmutatiewaardering wordt een positief verschil tussen verkrijgingsprijs en de bedoelde waarde als goodwill geactiveerd. Afschrijving volgt de verwachte gebruiksduur; maximaal tien jaar is alleen de genoemde uitzonderingssituatie bij een niet betrouwbaar te schatten gebruiksduur. De wettelijke reserve deelneming houdt rekening met de in lid 6 genoemde vermogensvermeerderingen, verminderingen en beschikbare uitkeringen.</p>${lawLink('389','lid 6 en 7')} ${lawLink('386','lid 3')}</details><details><summary>Op welke balansrubriek?</summary><p>Beoordeel de bestemming: duurzaam dienstbaar aan de werkzaamheid of niet? De wet onderscheidt financiële vaste activa, waaronder deelnemingen en overige effecten, en vlottende effecten. “Geen deelneming” betekent dus niet automatisch “vlottend”.</p>${lawLink('364','lid 1 t/m 3')} ${lawLink('367','onder a, b en e')} ${lawLink('371')}</details></div>
<p class="capital-bridge">Deze grondslagkeuze bepaalt of winst al doorwerkt in Deelneming en waarom dividend bij NVW niet nogmaals opbrengst is. Dat vormt later ook het verschil tussen de NVW- en verkrijgingsprijsmethode bij consolidatie.</p></div>
<div id="capital-consolidate" class="capital-stage"><h2>3. Wie consolideert welke gegevens?</h2>
${box('Staat een rechtspersoon aan het hoofd van een groep of groepsdeel?','Werk plicht en kring afzonderlijk uit. Bij het groepshoofd geldt lid 1. Bij de in lid 2 bedoelde rechtspersoon binnen de groep geldt de verplichting voor het groepsdeel. Neem de eigen cijfers op met de in het toepasselijke lid genoemde maatschappijen; niet uitsluitend de belangen boven 50%.',[['406','lid 1 en 2']],'capital-decision')}
${arrow('Plicht en kring vastgesteld? Toets dan de uitzonderingen.')}
<div class="capital-parallel"><article class="capital-lane"><h3>Gegevens buiten de kring?</h3><p>Gezamenlijk te verwaarlozen betekenis, onevenredige kosten/grote vertraging, of een belang dat slechts voor vervreemding wordt gehouden: toets de specifieke voorwaarden, geen automatische vrijstelling.</p>${lawLink('407','lid 1')}</article><article class="capital-lane"><h3>Consolidatie achterwege?</h3><p>Voor een kleine groep: alle voorwaarden van artikel 2:407 lid 2. Voor een groepsdeel binnen een groter geheel: alle voorwaarden en beperkingen van artikel 2:408. Een 403-verklaring beantwoordt een andere vraag.</p>${lawLink('407','lid 2')} ${lawLink('408','lid 1, 3 en 4')} ${lawLink('403')}</article><article class="capital-lane"><h3>Gezamenlijke bevoegdheden?</h3><p>Bij een samenwerking volgens artikel 2:409 kan proportionele consolidatie worden toegepast als ook het inzichtvereiste is vervuld. Een 50/50-verhouding alleen bewijst die voorwaarden niet.</p>${lawLink('409','onder a en b')}</article></div>
${arrow('Daarna: samenvoegen, elimineren en toerekenen.')}
${box('De groep als één geheel','Verwijder onderlinge posities en nog interne winsten uit de opgenomen cijfers. Presenteer het niet aan de moeder toekomende deel van groepsvermogen en resultaat afzonderlijk. Dit is de verbinding met het IC-kernschema.',[['405','lid 1 en 2'],['411','lid 2']])}
<p><a class="study-button primary" href="#kernschema">Naar IC-kernschema →</a> <a class="study-button" href="#consolidatieplicht">Uitleg consolidatieplicht</a> <a class="study-button" href="index.html#kap-1">Oefen kapitaalbelangen</a></p>
</div><details class="capital-source-note"><summary>Bronnen en reikwijdte</summary><p>Gebaseerd op de aangeleverde studieversie van Boek 2 BW en Syllabus CAFA2 Deel 1, met aansluiting op Deel 3. Vindplaatsen: Syllabus CAFA2 Deel 1, p. 4–14 (kwalificatie en invloed), p. 15–27 (waardering, goodwill en reserves) en p. 31–36 (consolidatie). Boek 2 BW: de exacte pagina staat op iedere artikelverwijzing. De korte toelichtingen hieronder en in de boom zijn geen letterlijke wettekst.</p><p>Voor de accountant ligt de samenhang in het toetsen van inzicht en wettelijke voorschriften. De tekstuele uitleg in de boom is een toelichting op de genoemde bronnen; de gekleurde verwijzingen tonen de wettekst.</p>${lawLink('393','lid 3')} ${lawLink('362','lid 1')}</details>
</section>`;}
