(function(){'use strict';
var DATA=window.CAFA2_DATA;if(!DATA||!DATA.modules)return;var BANKS=DATA.modules,KEY=DATA.id;
var root=document.documentElement,$=function(s,p){return(p||document).querySelector(s)},all=function(s,p){return Array.prototype.slice.call((p||document).querySelectorAll(s))};
var codes=Object.keys(BANKS),boot=true,canSave=true,lastCode='kap',pendingFinish=null;
var state={v:1,id:KEY,font:14,studyMode:'practice',modules:{}};
function freshModule(){return {answers:{},current:1,exam:false,finished:false,finishedAt:null,started:0,attempt:1,history:[]};}
codes.forEach(function(c){state.modules[c]=freshModule();});
function valid(c,id){return BANKS[c]&&Number.isInteger(+id)&&+id>=1&&+id<=30;}
function blankAnswer(){return {choice:null,mode:'mc',marked:false,text:'',html:'',rows:[],firstMC:null,firstSelf:null,checked:false,view:null};}
function richText(html){var template=document.createElement('template');template.innerHTML=html;var box=template.content;all('br',box).forEach(function(el){el.replaceWith('\n');});all('td,th',box).forEach(function(el){el.appendChild(document.createTextNode('\t'));});all('p,div,li,tr,h2,h3,h4,blockquote',box).forEach(function(el){el.appendChild(document.createTextNode('\n'));});return(box.textContent||'').replace(/[\t ]+\n/g,'\n').replace(/\n{3,}/g,'\n\n').trim();}
function sanitizeRich(html){return window.CafaAnswerEditor?window.CafaAnswerEditor.sanitize(html):esc(richText(String(html||''))).replace(/\n/g,'<br>');}
function cleanAnswer(c,i,a){var b=blankAnswer();if(!a||typeof a!=='object')return b;
 if(Number.isInteger(a.choice)&&a.choice>=0&&a.choice<4)b.choice=a.choice;b.mode=a.mode==='own'?'own':'mc';b.marked=!!a.marked;b.checked=!!a.checked;
 b.text=typeof a.text==='string'?a.text:typeof a.editor==='string'?a.editor:'';
 if(typeof a.html==='string'){b.html=sanitizeRich(a.html);if(b.html)b.text=richText(b.html);}
 b.rows=Array.isArray(a.rows)?a.rows.slice(0,100).map(function(r){return Array.isArray(r)?r.slice(0,3).map(function(v){return String(v).slice(0,500)}):['','',''];}):[];
 if(a.firstMC&&Number.isInteger(a.firstMC.choice)&&a.firstMC.choice>=0&&a.firstMC.choice<4){b.firstMC={choice:a.firstMC.choice,correct:a.firstMC.choice===BANKS[c].questions[i-1].correct,at:String(a.firstMC.at||'')};}
 else if(a.first&&a.first.kind==='auto'&&Number.isInteger(a.first.choice)&&a.first.choice>=0&&a.first.choice<4){b.firstMC={choice:a.first.choice,correct:a.first.choice===BANKS[c].questions[i-1].correct,at:String(a.first.at||'')};}
 var fs=a.firstSelf||(a.first&&a.first.kind==='self'?a.first:null);if(fs)b.firstSelf={correct:!!fs.correct,at:String(fs.at||'')};
 if(a.view==='all'||/^[0-3]$/.test(String(a.view)))b.view=String(a.view);return b;
}
function cleanHistory(c,history){return(Array.isArray(history)?history:[]).slice(-30).filter(function(h){return h&&typeof h==='object';}).map(function(h){var answers={};if(h.answers&&typeof h.answers==='object')Object.keys(h.answers).forEach(function(id){if(valid(c,id))answers[id]=cleanAnswer(c,+id,h.answers[id]);});return{at:typeof h.at==='string'?h.at:'',attempt:Math.max(1,Number(h.attempt)||1),finished:h.finished===true,finishedAt:typeof h.finishedAt==='string'&&Number.isFinite(Date.parse(h.finishedAt))?h.finishedAt:null,answers:answers};});}
function cleanModule(c,m){var z=freshModule();if(!m||typeof m!=='object')return z;
 z.current=valid(c,m.current)?+m.current:1;z.exam=!!m.exam;z.finished=!!m.finished;z.finishedAt=typeof m.finishedAt==='string'&&Number.isFinite(Date.parse(m.finishedAt))?m.finishedAt:null;z.started=Number(m.started)||0;z.attempt=Math.max(1,Number(m.attempt)||1);z.history=cleanHistory(c,m.history);
 if(m.answers&&typeof m.answers==='object')Object.keys(m.answers).forEach(function(id){if(valid(c,id))z.answers[id]=cleanAnswer(c,+id,m.answers[id]);});return z;
}
try{var stored=localStorage.getItem(KEY);if(stored){var parsed=JSON.parse(stored);if(parsed.id===KEY&&parsed.modules){codes.forEach(function(c){state.modules[c]=cleanModule(c,parsed.modules[c]);});state.font=Number(parsed.font)||14;state.studyMode=parsed.studyMode==='exam'?'exam':'practice';}}}catch(e){canSave=false;}
function a(c,i){var m=state.modules[c];return m.answers[i]||(m.answers[i]=blankAnswer());}
function current(){var m=location.hash.match(/^#(kap|val|nvw|hk)-(\d+)$/);return m&&valid(m[1],m[2])?{code:m[1],id:+m[2]}:null;}
function ownHas(x){return !!x.text.trim()||x.rows.some(function(r){return r.some(function(v){return String(v).trim();});});}
function isAnswered(x){return x.choice!==null||ownHas(x);}
function metrics(c){var r={answered:0,auto:0,good:0,self:0,selfGood:0,marked:0};BANKS[c].questions.forEach(function(q){var x=a(c,q.id);if(isAnswered(x))r.answered++;if(x.marked)r.marked++;if(x.firstMC){r.auto++;if(x.firstMC.correct)r.good++;}if(x.firstSelf){r.self++;if(x.firstSelf.correct)r.selfGood++;}});return r;}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));canSave=true;}catch(e){canSave=false;}all('[data-save-status]').forEach(function(el){el.textContent=canSave?'Voortgang wordt op dit apparaat bewaard.':'Opslaan is geblokkeerd; gebruik Voortgang om een back-up te maken.';});window.dispatchEvent(new CustomEvent('cafa:practice-change'));}
function esc(s){return String(s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function status(c,id){var x=a(c,id),m=state.modules[c];if(m.exam&&!m.finished)return isAnswered(x)?'Beantwoord':'Niet beantwoord';if(x.firstMC)return x.firstMC.correct?'Goed':'Fout';if(x.firstSelf)return x.firstSelf.correct?'Goed · zelf':'Oefenen · zelf';return isAnswered(x)?'Beantwoord':'Niet beantwoord';}
function refresh(){var cur=current();if(cur)lastCode=cur.code;codes.forEach(function(c){var r=metrics(c),m=state.modules[c];
 all('[data-topic-progress="'+c+'"]').forEach(function(el){el.textContent=r.answered+' / 30 beantwoord'+((!m.exam||m.finished)&&r.auto?' · '+r.good+'/'+r.auto+' goed':'');});
 all('[data-start="'+c+'"]').forEach(function(el){el.href='#'+c+'-'+(m.current||1);el.textContent=(r.answered||m.started)?'Verder':'Start';});
 all('[data-inline-score="'+c+'"]').forEach(function(el){el.textContent=m.exam&&!m.finished?'Tentamenstand':'Goed: '+r.good+'/'+r.auto;});
 all('[data-return="'+c+'"]').forEach(function(el){el.href='#'+c+'-'+(m.current||1);});
 all('[data-overview-count="'+c+'"]').forEach(function(el){el.textContent=r.answered+' van 30 beantwoord · '+(30-r.answered)+' niet beantwoord · '+r.marked+' gemarkeerd';});
 BANKS[c].questions.forEach(function(q){var x=a(c,q.id),el=document.getElementById(c+'-'+q.id);if(!el)return;
 el.classList.toggle('is-exam',m.exam);el.classList.toggle('is-finished',m.finished);
 var cs=$('[data-choice-status]',el);if(cs)cs.textContent=x.choice!==null?'Gekozen: '+String.fromCharCode(65+x.choice):'Nog geen keuze';
 all('[data-score-note]',el).forEach(function(n){n.textContent=x.firstMC?'Eerste beoordeling: '+(x.firstMC.correct?'goed':'fout')+'. Tussenstand: '+r.good+' / '+r.auto+' goed.':'';});
 all('[data-self-note]',el).forEach(function(n){n.textContent=x.firstSelf?'Zelfbeoordeeld: '+(x.firstSelf.correct?'goed':'opnieuw oefenen')+'. Zelfbeoordeling blijft apart van de meerkeuzescore.':'';});
 });
 });
 all('[data-nav]').forEach(function(el){var parts=el.dataset.nav.split('-'),c=parts[0],id=+parts[1],x=a(c,id),isCurrent=!!cur&&cur.code===c&&cur.id===id;el.classList.toggle('answered',isAnswered(x));el.classList.toggle('marked',x.marked);el.classList.toggle('current',isCurrent);if(isCurrent)el.setAttribute('aria-current','step');else el.removeAttribute('aria-current');el.setAttribute('aria-label','Vraag '+id+': '+BANKS[c].questions[id-1].title+'. '+status(c,id)+(x.marked?', gemarkeerd':''));var st=$('.ov-status',el);if(st)st.textContent=isAnswered(x)?'Beantwoord':'Niet beantwoord';});
 var r=metrics(lastCode),m=state.modules[lastCode];all('[data-top-score]').forEach(function(el){el.textContent=cur?(m.exam&&!m.finished?'Tentamenstand':'Goed: '+r.good+' / '+r.auto):'120 vragen';});
}
function review(c,id){var x=a(c,id);if(x.choice===null)return false;var m=state.modules[c];if(m.exam&&!m.finished)return false;x.checked=true;if(!x.firstMC)x.firstMC={choice:x.choice,correct:x.choice===BANKS[c].questions[id-1].correct,at:new Date().toISOString()};save();refresh();return true;}
function selfGrade(c,id,good){var x=a(c,id);if(!ownHas(x)){alert('Werk eerst je eigen antwoord uit.');return;}if(!x.firstSelf)x.firstSelf={correct:good,at:new Date().toISOString()};save();refresh();}
function setView(el,x,view){x.view=view;el.classList.toggle('single-view',view!=='all');all('[data-view]',el).forEach(function(b){b.classList.toggle('active',b.dataset.view===view);b.setAttribute('aria-pressed',b.dataset.view===view?'true':'false');});all('.option',el).forEach(function(o){var shown=view==='all'||o.dataset.option===view;o.classList.toggle('is-visible',shown);o.setAttribute('aria-hidden',shown?'false':'true');});}
function storeOwn(el,c,id){var x=a(c,id),ed=$('.own-editor',el);var next=ed?ed.value:'';if(next!==x.text){x.text=next;x.html='';}x.rows=all('.entry-table tbody tr',el).map(function(row){return all('input',row).map(function(i){return i.value;});});save();refresh();}
function bindRow(row,el,c,id){all('input',row).forEach(function(input){input.addEventListener('input',function(){storeOwn(el,c,id);});});}
all('.question').forEach(function(el){var c=el.dataset.code,id=+el.dataset.q,x=a(c,id),rev=$('.mc-review',el);
 all('.answer-radio',el).forEach(function(r){r.checked=x.choice===+r.value;r.addEventListener('change',function(){x.choice=+r.value;if(rev)rev.open=false;if(el.classList.contains('single-view'))setView(el,x,r.value);save();refresh();});});
 all('.mode-radio',el).forEach(function(r){r.checked=r.value===x.mode;r.addEventListener('change',function(){x.mode=r.value;save();refresh();});});
 var flag=$('.flagbox',el);flag.checked=x.marked;flag.addEventListener('change',function(){x.marked=flag.checked;save();refresh();});
 if(rev)rev.addEventListener('toggle',function(){if(!boot&&rev.open)review(c,id);});
 var form=$('.mc-area',el);form.addEventListener('submit',function(e){e.preventDefault();});form.addEventListener('reset',function(){x.choice=null;if(rev)rev.open=false;setTimeout(function(){all('.answer-radio',el).forEach(function(i){i.checked=false;});save();refresh();},0);});
 all('[data-view]',el).forEach(function(b){b.addEventListener('click',function(){setView(el,x,b.dataset.view);save();});});
 setView(el,x,x.view||(window.matchMedia('(max-width:540px)').matches?'0':'all'));
 var ed=$('.own-editor',el);if(ed){ed.value=x.text;ed.addEventListener('input',function(){storeOwn(el,c,id);});}
 var tb=$('.entry-table tbody',el);if(tb){while(tb.rows.length<x.rows.length){tb.appendChild(tb.rows[0].cloneNode(true));}all('tr',tb).forEach(function(tr,ri){all('input',tr).forEach(function(input,ci){input.value=x.rows[ri]?x.rows[ri][ci]||'':'';});bindRow(tr,el,c,id);});var b=$('[data-add-row]',el);if(b)b.addEventListener('click',function(){if(tb.rows.length>=100)return;var row=tb.rows[0].cloneNode(true);all('input',row).forEach(function(i){i.value='';});tb.appendChild(row);bindRow(row,el,c,id);});}
 all('[data-self-grade]',el).forEach(function(b){b.addEventListener('click',function(){selfGrade(c,id,b.dataset.selfGrade==='good');});});
});
function setFont(v,store){state.font=Math.max(10,Math.min(24,Math.round(Number(v)||14)));root.style.setProperty('--base',state.font+'px');all('[data-font]').forEach(function(b){var k=+b.dataset.font;b.hidden=k===0&&state.font===14;b.disabled=(k<0&&state.font===10)||(k>0&&state.font===24);b.title=k===0?'Standaard: 14 px':'Huidige grootte: '+state.font+' px';});if(store)save();}
all('[data-font]').forEach(function(b){b.addEventListener('click',function(){var n=+b.dataset.font;setFont(n===0?14:state.font+n,true);});});setFont(state.font,false);
var sel=$('[data-study-mode]');sel.value=state.studyMode;sel.addEventListener('change',function(){state.studyMode=sel.value;save();});
all('[data-start]').forEach(function(link){link.addEventListener('click',function(){var c=link.dataset.start,m=state.modules[c];if(!m.started){m.started=Date.now();m.exam=state.studyMode==='exam';}save();refresh();});});
function renderResult(c){var d=BANKS[c],r=metrics(c),m=state.modules[c];if(m.exam&&!m.finished)return '<p class="notice">Dit onderwerp staat in tentamenstand. Je hebt '+r.answered+' van 30 vragen beantwoord. Voltooi het onderwerp om je antwoorden na te kijken.</p>';
var pct=r.auto?(r.good/r.auto*100).toFixed(1).replace('.',',')+'%':'Nog geen score';var s='<div class="stats-grid"><div class="stat"><b>'+r.good+' / '+r.auto+'</b><span>Goed van nagekeken meerkeuze</span></div><div class="stat"><b>'+pct+'</b><span>Percentage goed</span></div><div class="stat"><b>'+r.answered+' / 30</b><span>Beantwoord of uitgewerkt</span></div></div>';
if(r.self)s+='<p class="notice">Zelfbeoordeling: '+r.selfGood+' / '+r.self+' goed. Deze score staat apart van de automatisch gecontroleerde meerkeuzeantwoorden.</p>';
var wrong=d.questions.filter(function(q){var x=a(c,q.id);return(x.firstMC&&!x.firstMC.correct)||(x.firstSelf&&!x.firstSelf.correct);});if(wrong.length)s+='<div class="pattern"><b>Foutvragen en herhaling</b><div class="related">'+wrong.map(function(q){return '<a href="#'+c+'-'+q.id+'">'+q.id+' · '+esc(q.title)+'</a>';}).join('')+'</div></div>';
s+='<p class="small" style="margin:12px 0">Oorspronkelijke meerkeuzescore per onderwerp. Herhalen verandert de eerste beoordeling niet. Open vragen tellen tijdens het oefenen niet als fout.</p>';
d.questions.forEach(function(q){var x=a(c,q.id),cl=x.firstMC?(x.firstMC.correct?'good':'bad'):'';s+='<a class="result-row" href="#'+c+'-'+q.id+'"><span>'+q.id+'</span><span>'+esc(q.title)+'</span><span class="result-status '+cl+'">'+esc(status(c,q.id))+'</span></a>';});return s;}
function resultRefresh(){codes.forEach(function(c){var el=$('[data-results="'+c+'"]');if(el)el.innerHTML=renderResult(c);});var total={good:0,auto:0,answered:0,self:0,selfGood:0};codes.forEach(function(c){var r=metrics(c);Object.keys(total).forEach(function(k){total[k]+=r[k];});});var s='<div class="stats-grid"><div class="stat"><b>'+total.good+' / '+total.auto+'</b><span>Goed van nagekeken meerkeuze</span></div><div class="stat"><b>'+total.answered+' / 120</b><span>Beantwoord of uitgewerkt</span></div><div class="stat"><b>'+total.selfGood+' / '+total.self+'</b><span>Zelfbeoordeeld goed</span></div></div>';codes.forEach(function(c){var r=metrics(c);s+='<a class="result-row" href="#resultaat-'+c+'"><span>'+BANKS[c].opgave+'</span><span>'+esc(BANKS[c].title)+'</span><span class="result-status">'+r.good+' / '+r.auto+'</span></a>';});$('[data-all-results]').innerHTML=s;}
var ov=$('#overview-dialog');function openOverview(c){refresh();$('[data-dialog-topic]',ov).textContent='· '+BANKS[c].title;var box=$('[data-dialog-list]',ov),src=$('#overzicht-'+c);box.innerHTML='';['[data-overview-count]','.overview-list','.legend'].forEach(function(selector){var el=$(selector,src);if(el)box.appendChild(el.cloneNode(true));});all('a',box).forEach(function(el){el.addEventListener('click',function(){ov.close();});});if(ov.showModal)ov.showModal();else location.hash='overzicht-'+c;}
all('[data-overview]').forEach(function(link){link.addEventListener('click',function(e){if(ov.showModal){e.preventDefault();openOverview(link.dataset.overview);}});});all('[data-close-overview]').forEach(function(b){b.addEventListener('click',function(){ov.close();});});ov.addEventListener('click',function(e){if(e.target===ov)ov.close();});
var fd=$('#finish-dialog');function finish(c){var m=state.modules[c];m.finished=true;if(!m.finishedAt)m.finishedAt=new Date().toISOString();BANKS[c].questions.forEach(function(q){if(a(c,q.id).choice!==null)review(c,q.id);});save();refresh();resultRefresh();location.hash='resultaat-'+c;}
all('[data-finish]').forEach(function(b){b.addEventListener('click',function(){var c=b.dataset.finish,r=metrics(c);pendingFinish=c;$('[data-finish-message]',fd).textContent=BANKS[c].title+': '+r.answered+' van 30 beantwoord; '+r.marked+' gemarkeerd.';if(fd.showModal)fd.showModal();else if(confirm('Dit onderwerp voltooien en alle gekozen antwoorden nakijken?'))finish(c);});});all('[data-cancel-finish]').forEach(function(b){b.addEventListener('click',function(){fd.close();pendingFinish=null;});});$('[data-confirm-finish]').addEventListener('click',function(){if(!pendingFinish)return;var c=pendingFinish;fd.close();pendingFinish=null;finish(c);});
all('[data-reset]').forEach(function(b){b.addEventListener('click',function(){var c=b.dataset.reset;if(!confirm('Een nieuwe poging voor '+BANKS[c].title+' starten? Bewaar zo nodig eerst je resultaatbestand. De andere onderwerpen blijven ongewijzigd.'))return;var old=state.modules[c],hist=old.history||[];hist.push({at:new Date().toISOString(),attempt:old.attempt,finished:old.finished,finishedAt:old.finishedAt,metrics:metrics(c),answers:old.answers});state.modules[c]=freshModule();state.modules[c].attempt=old.attempt+1;state.modules[c].history=hist.slice(-30);save();location.hash='start';location.reload();});});
function pack(){var out={bank:KEY,version:1,exported:new Date().toISOString(),title:'CAFA2 MC vragen',state:state,subjects:{}};codes.forEach(function(c){out.subjects[c]={title:BANKS[c].title,summary:metrics(c),questions:BANKS[c].questions.map(function(q){return{number:q.id,title:q.title,type:q.type,answer:a(c,q.id),sources:q.refs.map(function(r){return BANKS[c].sources[r].label;})};})};});return out;}
function download(name,text){var u=URL.createObjectURL(new Blob([text],{type:'application/json;charset=utf-8'})),link=document.createElement('a');link.href=u;link.download=name;document.body.appendChild(link);link.click();link.remove();setTimeout(function(){URL.revokeObjectURL(u)},15000);}
function summaryText(){var lines=['CAFA2 MC vragen - voortgang','Datum: '+new Date().toLocaleString('nl-NL'),''];codes.forEach(function(c){var r=metrics(c);lines.push('Opgave '+BANKS[c].opgave+': '+BANKS[c].title,'Meerkeuze: '+r.good+' / '+r.auto+' goed; '+r.answered+' / 30 beantwoord.','Zelfbeoordeling: '+r.selfGood+' / '+r.self+' goed.');BANKS[c].questions.forEach(function(q){var x=a(c,q.id);if(!isAnswered(x)&&!x.firstMC&&!x.firstSelf)return;lines.push('Vraag '+q.id+' ('+q.title+'): '+status(c,q.id));if(x.firstMC)lines.push('Eerste meerkeuze: '+String.fromCharCode(65+x.firstMC.choice)+(x.firstMC.correct?' (goed)':' (fout)'));if(x.text.trim())lines.push('Eigen antwoord: '+x.text);if(x.rows.some(function(r){return r.some(Boolean)}))lines.push(x.rows.filter(function(r){return r.some(Boolean)}).map(function(r){return r.join(' | ')}).join('\n'));});lines.push('');});return lines.join('\n');}
all('[data-export]').forEach(function(b){b.addEventListener('click',function(){download('CAFA2 voortgang.json',JSON.stringify(pack(),null,2));});});all('[data-export-text]').forEach(function(b){b.addEventListener('click',function(){var x=$('#export-text');x.hidden=false;x.value=summaryText();x.focus();x.select();});});
all('[data-import]').forEach(function(input){input.addEventListener('change',function(){var file=input.files&&input.files[0];if(!file)return;if(file.size>10000000){alert('Dit bestand is te groot. Kies een geëxporteerd CAFA2-resultaatbestand.');return;}var reader=new FileReader();reader.onload=function(){try{var obj=JSON.parse(reader.result),msg='';if(obj.bank===KEY&&obj.state&&obj.state.modules){if(!confirm('De voortgang van de vier onderwerpen vervangen door dit resultaatbestand?'))return;codes.forEach(function(c){state.modules[c]=cleanModule(c,obj.state.modules[c]);});state.font=Number(obj.state.font)||14;msg='Alle onderwerpen ingelezen.';}else{var c=codes.find(function(code){return obj.bank===BANKS[code].id;});if(!c||!obj.state||!obj.state.answers)throw Error('Deze export hoort niet bij een van deze toetsen.');if(!confirm('Voortgang voor '+BANKS[c].title+' vervangen door deze oude export?'))return;state.modules[c]=cleanModule(c,obj.state);msg=BANKS[c].title+' ingelezen.';}save();location.hash='start';location.reload();}catch(e){$('[data-import-message]').textContent='Niet ingelezen: '+e.message;}};reader.readAsText(file);});});
window.addEventListener('hashchange',function(){var cur=current();if(cur){var m=state.modules[cur.code];m.current=cur.id;lastCode=cur.code;if(!m.started){m.started=Date.now();m.exam=state.studyMode==='exam';}save();}refresh();if(location.hash.indexOf('#result')===0)resultRefresh();window.scrollTo(0,0);});
var cur=current();if(cur){lastCode=cur.code;state.modules[cur.code].current=cur.id;}
root.classList.add('enhanced');refresh();resultRefresh();save();boot=false;
function snapshotMetrics(answers){var r={answered:0,auto:0,good:0,self:0,selfGood:0,marked:0};Object.keys(answers||{}).forEach(function(id){var x=answers[id];if(isAnswered(x))r.answered++;if(x.marked)r.marked++;if(x.firstMC){r.auto++;if(x.firstMC.correct)r.good++;}if(x.firstSelf){r.self++;if(x.firstSelf.correct)r.selfGood++;}});return r;}
function completedAttempts(){var rows=[];codes.forEach(function(c){var m=state.modules[c];function append(attempt,isCurrent){if(!attempt.finished)return;var stats=snapshotMetrics(attempt.answers);rows.push({id:'practice-'+c+'-'+attempt.attempt,title:'CAFA2 oefenvragen · '+BANKS[c].title,code:c,attempt:attempt.attempt,submittedAt:attempt.finishedAt||null,answered:stats.answered,good:stats.good,total:30,auto:stats.auto,self:stats.self,selfGood:stats.selfGood,href:isCurrent?'#resultaat-'+c:null,summary:stats,answers:attempt.answers});}m.history.forEach(function(h){append(h,false);});append(m,true);});return JSON.parse(JSON.stringify(rows));}
window.CafaPractice={
 getCompleted:completedAttempts,
 getAnswer:function(c,id){return valid(c,id)?JSON.parse(JSON.stringify(a(c,id))):null;},
 setRichAnswer:function(c,id,html){if(!valid(c,id))return;var x=a(c,id);x.html=sanitizeRich(html);x.text=richText(x.html);var ed=$('.own-editor',document.getElementById(c+'-'+id));if(ed)ed.value=x.text;save();refresh();},
 toggleMarked:function(c,id){if(!valid(c,id))return;var flag=$('.flagbox',document.getElementById(c+'-'+id));if(flag){flag.checked=!flag.checked;flag.dispatchEvent(new Event('change',{bubbles:true}));}},
 getSaveStatus:function(){return canSave;}
};
window.cafaAppTest={metrics:metrics,current:current,bank:DATA,getState:function(){return state},refresh:refresh,resultRefresh:resultRefresh};
})();
