(function(){
  'use strict';
  var columns=['Omschrijving grootboekrekening','Debet','Credit','Ruimte voor eventuele toelichting'];
  function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
  function supports(q){return q.type==='open' && /journaalpost|eliminatieboeking|correctieboeking/.test(q.prompt.toLowerCase());}
  function normalize(rows){return Array.from({length:Math.max(8,Math.min(100,Array.isArray(rows)?rows.length:0))},function(_,i){return columns.map(function(_,j){return rows&&Array.isArray(rows[i])&&typeof rows[i][j]==='string'?rows[i][j]:'';});});}
  function render(rows,readonly){rows=normalize(rows);return '<div class="journal-scroll" tabindex="0" aria-label="Journaalpostentabel, horizontaal schuifbaar"><table class="journal-table"><thead><tr>'+columns.map(function(c){return '<th scope="col">'+c+'</th>';}).join('')+'</tr></thead><tbody>'+rows.map(function(row,i){return '<tr>'+row.map(function(cell,j){return '<td>'+(readonly?'<span>'+esc(cell)+'</span>':'<input type="text" '+(j===1||j===2?'inputmode="decimal" ':'')+'aria-label="Rij '+(i+1)+', '+columns[j]+'" data-journal-row="'+i+'" data-journal-col="'+j+'" value="'+esc(cell)+'">')+'</td>';}).join('')+'</tr>';}).join('')+'</tbody></table></div>'+(readonly?'':'<button type="button" class="btn journal-add">+ Rij toevoegen</button>');}
  function mount(host,rows,onChange){var current=normalize(rows);host.innerHTML=render(current,false);host.addEventListener('input',function(e){if(!e.target.matches('[data-journal-row]'))return;current[Number(e.target.dataset.journalRow)][Number(e.target.dataset.journalCol)]=e.target.value;onChange(current.map(function(r){return r.slice();}));});host.addEventListener('click',function(e){if(!e.target.closest('.journal-add')||current.length>=100)return;current.push(['','','','']);host.innerHTML=render(current,false);onChange(current.map(function(r){return r.slice();}));host.querySelector('[data-journal-row="'+(current.length-1)+'"]').focus();});}
  window.CafaJournalTable={supports:supports,render:render,mount:mount};
}());
