(function(){
  'use strict';
  var topics=window.CAFA2_TOPICS||[],KEY='cafa2-topic-routes-v1',state={active:null,topics:{}},mounted=false,originals={},painted=null;
  var $=function(s,p){return(p||document).querySelector(s);},all=function(s,p){return Array.from((p||document).querySelectorAll(s));};
  var esc=function(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});};
  function source(uid){var p=split(uid),q=p&&window.CAFA2_DATA.modules[p.code].questions[p.id-1];return q&&q.sourceType==='exam'?'exam':'syllabus';}
  function matchesSource(uid){return !state.sourceFilter||state.sourceFilter==='all'||source(uid)===state.sourceFilter;}
  function get(id){var t=topics.find(function(t){return t.id===id;});if(t)return t;var m=/^deel-(kap|val|nvw|hk)$/.exec(id);if(m){var b=window.CAFA2_DATA.modules[m[1]];return{id:id,title:b.title,questions:b.questions.map(function(q){return m[1]+'-'+q.id;}).filter(matchesSource)};}return null;}
  function save(){try{localStorage.setItem(KEY,JSON.stringify(state));}catch(_){}}
  try{var old=JSON.parse(localStorage.getItem(KEY)||'null');if(old&&old.topics&&typeof old.topics==='object'){state.topics=old.topics;state.sourceFilter=['all','syllabus','exam'].includes(old.sourceFilter)?old.sourceFilter:'all';state.active=get(old.active)?old.active:null;}}catch(_){}
  function session(t){var key=t.id+((state.sourceFilter&&state.sourceFilter!=='all')?':'+state.sourceFilter:'');var s=state.topics[key];if(!s||typeof s!=='object')s=state.topics[key]={current:t.questions[0],exam:false,finished:false,started:false};if(!t.questions.includes(s.current))s.current=t.questions[0];return s;}
  function split(uid){var m=/^(kap|val|nvw|hk)-(\d+)$/.exec(uid);return m?{code:m[1],id:+m[2]}:null;}
  function answer(uid){var p=split(uid);return p&&window.CafaPractice?window.CafaPractice.getAnswer(p.code,p.id):null;}
  function answered(a){return !!a&&(a.choice!==null||a.text.trim()||a.rows.some(function(r){return r.some(Boolean);}));}
  function stats(t){var s={answered:0,checked:0,good:0,marked:0};t.questions.forEach(function(uid){var a=answer(uid);if(!a)return;if(answered(a))s.answered++;if(a.firstMC){s.checked++;if(a.firstMC.correct)s.good++;}if(a.marked)s.marked++;});return s;}
  function context(c,id){var t=get(state.active);return t&&t.questions.includes(c+'-'+id)?session(t):null;}
  function persistMode(t){var s=session(t);if(!s.started){s.started=true;s.exam=window.CafaPractice.getStudyMode()==='exam';s.finished=false;}return s;}
  function activate(t){state.active=t.id;persistMode(t);save();if(window.CafaPractice)window.CafaPractice.refresh();}
  function clear(){state.active=null;save();restore();}
  function restore(){if(!painted)return;var el=document.getElementById(painted),o=originals[painted];if(el&&o){$('.practice-page-title',el).textContent=o.title;$('.qnum',el).textContent=o.number;$('.question-count',el).innerHTML=o.count;$('.question-count',el).setAttribute('aria-label',o.label);all('.nav-left a',el).forEach(function(a,i){a.href=o.nav[i];});var crumb=$('.topic-question-context',el);if(crumb)crumb.remove();}painted=null;}
  function decorate(){
    restore();var uid=location.hash.slice(1),t=get(state.active),el=document.getElementById(uid);if(!t||!el||!t.questions.includes(uid))return;
    var index=t.questions.indexOf(uid),s=session(t);s.current=uid;save();
    var title=$('.practice-page-title',el),count=$('.question-count',el);if(!title||!count)return;
    if(!originals[uid])originals[uid]={number:$('.qnum',el).textContent,title:title.textContent,count:count.innerHTML,label:count.getAttribute('aria-label'),nav:all('.nav-left a',el).map(function(a){return a.getAttribute('href');})};
    title.textContent=t.title;$('.qnum',el).textContent=index+1;count.innerHTML='VRAAG <span>'+(index+1)+'</span> VAN <span>'+t.questions.length+'</span>';count.setAttribute('aria-label','Vraag '+(index+1)+' van '+t.questions.length);
    var crumb=document.createElement('nav');crumb.className='topic-question-context';crumb.setAttribute('aria-label','Onderwerpnavigatie');crumb.innerHTML='<a href="#onderwerp-overzicht-'+t.id+'">Vragenoverzicht van dit onderwerp</a>';
    title.insertAdjacentElement('afterend',crumb);
    var nav=all('.nav-left a',el);if(nav[0])nav[0].href=index?'#'+t.questions[index-1]:'#onderwerp-overzicht-'+t.id;if(nav[1])nav[1].href=index+1<t.questions.length?'#'+t.questions[index+1]:'#onderwerp-resultaat-'+t.id;
    painted=uid;paintScore();
  }
  function paintScore(){if(!mounted)return;var t=get(state.active),uid=location.hash.slice(1),el=document.getElementById(uid);if(!t||!el||!t.questions.includes(uid))return;var r=stats(t),s=session(t),label=s.exam&&!s.finished?'Tentamenstand':'Goed: '+r.good+'/'+r.checked;all('[data-inline-score]',el).concat(all('[data-top-score]')).forEach(function(n){n.textContent=label;});all('[data-score-note]',el).forEach(function(n){var a=answer(uid);n.textContent=a.firstMC?'Eerste beoordeling: '+(a.firstMC.correct?'goed':'fout')+'. Onderwerp: '+r.good+' / '+r.checked+' goed.':'';});}
  function examDetails(t){var f=t.frequency;if(!f)return '';var id='topic-exams-'+t.id;return '<p class="topic-exam-label">Voorkomen onderwerp:</p><div class="topic-exam-sources"><button class="topic-exam-toggle" type="button" aria-expanded="false" aria-controls="'+id+'" aria-label="'+f.count+' van '+f.total+' tentamens: '+esc(t.title)+'">'+f.count+' van '+f.total+' tentamens</button><p class="topic-exam-codes" id="'+id+'" hidden>'+(f.count?f.exams.map(function(e){return'<span>'+esc(e.id)+'</span>';}).join(' · '):'Geen')+'</p></div>';}
  function topicCard(t,number){if(!t.questions.length)return '<article class="topic-card topic-detail-card" data-topic="'+t.id+'"><div class="topic-top"><span class="topic-n">'+number+'</span><h4>'+esc(t.title)+'</h4></div><p class="topic-description">'+esc(t.description)+'</p><p>Geen vragen voor dit filter.</p></article>';var r=stats(t),s=session(t);return'<article class="topic-card topic-detail-card" data-topic="'+t.id+'"><div class="topic-top"><span class="topic-n">'+number+'</span><h4>'+esc(t.title)+'</h4></div><p class="topic-description">'+esc(t.description)+'</p>'+examDetails(t)+'<div class="topic-footer"><p class="topic-progress">'+r.answered+' / '+t.questions.length+' beantwoord'+((!s.exam||s.finished)&&r.checked?' · '+r.good+'/'+r.checked+' goed':'')+'</p><div class="actions"><a class="btn primary" href="#onderwerp-'+t.id+'">'+(r.answered?'Verder':'Start')+'</a>'+(r.answered?'<button class="btn compact" type="button" data-topic-reset="'+t.id+'">Opnieuw beginnen</button>':'')+'<a class="btn compact" href="#onderwerp-overzicht-'+t.id+'" aria-label="Vragenoverzicht '+esc(t.title)+'">Overzicht</a></div></div></article>';}
  function renderCards(){paintModules();var host=$('#practice-topic-cards');if(!host)return;var number=0;host.innerHTML=(window.CAFA2_TOPIC_GROUPS||[]).map(function(group){return'<section class="topic-group" data-topic-group="'+group.id+'" aria-labelledby="topic-group-'+group.id+'"><div class="topic-group-heading"><h3 class="topic-group-title" id="topic-group-'+group.id+'">'+esc(group.title)+'</h3><p class="topic-group-source">'+esc(group.sourceLabel)+'</p></div><div class="topic-grid">'+group.topics.map(function(id){return topicCard(get(id),++number);}).join('')+'</div></section>';}).join('');}
  function questionTitle(uid){var p=split(uid);return window.CAFA2_DATA.modules[p.code].questions[p.id-1].title;}
  function overview(t){var s=session(t),r=stats(t),el=document.getElementById('onderwerp-overzicht-'+t.id);el.innerHTML='<div class="overview-top"><h1>'+esc(t.title)+'</h1><a class="btn" href="#oefenen">Alle onderwerpen</a></div><p>'+r.answered+' van '+t.questions.length+' beantwoord · '+r.marked+' gemarkeerd</p><div class="topic-question-list">'+t.questions.map(function(uid,i){var a=answer(uid),done=answered(a);return '<a class="result-row" href="#'+uid+'"><span>'+(i+1)+'</span><span>'+esc(questionTitle(uid))+'</span><span>'+(a.marked?'⚑ ':'')+((!s.exam||s.finished)&&a.firstMC?(a.firstMC.correct?'Goed':'Fout'):done?'Beantwoord':'Niet beantwoord')+'</span></a>';}).join('')+'</div><div class="actions"><a class="btn primary" href="#onderwerp-'+t.id+'">Verder oefenen</a><a class="btn" href="#onderwerp-resultaat-'+t.id+'">Resultaten</a></div>';}
  function result(t){var s=session(t),r=stats(t),el=document.getElementById('onderwerp-resultaat-'+t.id),hidden=s.exam&&!s.finished;el.innerHTML='<div class="overview-top"><h1>'+esc(t.title)+'</h1><a class="btn" href="#oefenen">Alle onderwerpen</a></div><p>'+r.answered+' van '+t.questions.length+' beantwoord.</p>'+(hidden?'<p class="notice">Voltooi dit onderwerp om de antwoorden en uitwerkingen te bekijken.</p>':'<p class="topic-score"><strong>'+r.good+' / '+r.checked+'</strong> goed van nagekeken meerkeuzevragen.</p><p>De eerste beoordeling blijft bewaard. Zelfbeoordeling telt niet mee in deze meerkeuzescore.</p>')+'<div class="actions"><button class="btn primary" type="button" data-topic-finish="'+t.id+'">'+(s.finished?'Alle gekozen antwoorden nakijken':'Onderwerp voltooien en nakijken')+'</button><a class="btn" href="#onderwerp-overzicht-'+t.id+'">Vragenoverzicht</a><a class="btn" href="#onderwerp-'+t.id+'">Verder oefenen</a></div>';
    if(!hidden){el.insertAdjacentHTML('beforeend','<div class="topic-question-list">'+t.questions.map(function(uid,i){var a=answer(uid);return'<a class="result-row" href="#'+uid+'"><span>'+(i+1)+'</span><span>'+esc(questionTitle(uid))+'</span><span>'+(a.firstMC?(a.firstMC.correct?'Goed':'Fout'):answered(a)?'Nog niet nagekeken':'Niet beantwoord')+'</span></a>';}).join('')+'</div>');}
  }
  function reset(t){if(!confirm('Opnieuw beginnen met '+t.title+'? De antwoorden, notities en scores van deze vragen worden gewist in zowel de onderwerpindeling als de vier delen. Andere vragen blijven bewaard. Exporteer zo nodig eerst je voortgang.'))return;var old=session(t),history=old.history||[];history.push({at:new Date().toISOString(),exam:old.exam,finished:old.finished,answers:Object.fromEntries(t.questions.map(function(uid){return[uid,answer(uid)];}))});Object.assign(session(t),{current:t.questions[0],exam:window.CafaPractice.getStudyMode()==='exam',finished:false,started:true,history:history.slice(-10)});state.active=t.id;save();window.CafaPractice.resetQuestions(t.questions);location.hash=t.questions[0];location.reload();}
  function finish(t){var r=stats(t);if(!window.confirm(t.title+': '+r.answered+' van '+t.questions.length+' beantwoord. Voltooien en alle gekozen antwoorden nakijken?'))return;var s=session(t);state.active=t.id;s.finished=true;save();t.questions.forEach(function(uid){var p=split(uid);window.CafaPractice.reviewQuestion(p.code,p.id);});window.CafaPractice.refresh();location.hash='onderwerp-resultaat-'+t.id;result(t);}
  function route(){if(!mounted)return;var h=location.hash.slice(1),match=/^onderwerp-(overzicht-|resultaat-)?(.+)$/.exec(h);if(match){var t=get(match[2]);if(!t)return;if(!t.questions.length){location.hash='oefenen';return;}activate(t);if(match[1]==='overzicht-')overview(t);else if(match[1]==='resultaat-')result(t);else{location.replace('#'+session(t).current);return;}}else if(h==='oefenen'||h==='start'||h==='dashboard'||/^overzicht-(kap|val|nvw|hk)$/.test(h)){clear();if(window.CafaPractice)window.CafaPractice.refresh();}
    else {var active=get(state.active);if(active&&(!split(h)||!active.questions.includes(h))){clear();if(window.CafaPractice)window.CafaPractice.refresh();}}
    decorate();if(h==='oefenen')renderCards();
  }
  function paintModules(){
    if(!mounted||!window.CafaPractice)return;
    Object.keys(window.CAFA2_DATA.modules).forEach(function(c){
      var t=get('deel-'+c),r=stats(t),m=window.CafaPractice.getModule(c),sessionState=state.sourceFilter&&state.sourceFilter!=='all'?session(t):m;
      all('[data-topic-progress="'+c+'"]').forEach(function(n){n.textContent=r.answered+' / '+t.questions.length+' beantwoord'+((!sessionState.exam||sessionState.finished)&&r.checked?' · '+r.good+'/'+r.checked+' goed':'');});
      all('[data-start="'+c+'"]').forEach(function(a){a.hidden=!t.questions.length;if(state.sourceFilter&&state.sourceFilter!=='all'){a.href='#'+session(t).current;a.textContent=r.answered?'Verder':'Start';}});
      all('#overzicht-'+c+' [data-nav]').forEach(function(a){a.hidden=!matchesSource(a.dataset.nav);});
    });
    var count=Object.keys(window.CAFA2_DATA.modules).reduce(function(n,c){return n+get('deel-'+c).questions.length;},0);
    var subtitle=$('#oefenen .home-sub');if(subtitle)subtitle.textContent='Vier delen · 19 onderwerpen · '+count+' oefenvragen'+(state.sourceFilter==='exam'?' · Tentamenvragen':state.sourceFilter==='syllabus'?' · Syllabusvragen':'');
  }
  function applyFilter(){
    topics.forEach(function(t){if(!t.allQuestions)t.allQuestions=t.questions.slice();t.questions=t.allQuestions.filter(matchesSource);});
    restore();state.active=null;save();renderCards();
  }
  function mountFilter(){
    var mode=$('#oefenen select[data-study-mode]'),label=mode&&mode.closest('label');if(!label)return;
    var controls=document.createElement('div');controls.className='practice-source-controls';label.before(controls);controls.append(label);
    var filter=document.createElement('label');filter.innerHTML='Filter op: <select data-practice-source aria-label="Bron van oefenvragen"><option value="all">Alle vragen</option><option value="syllabus">Syllabusvragen</option><option value="exam">Tentamenvragen</option></select>';controls.append(filter);
    var select=filter.querySelector('select');select.value=state.sourceFilter||'all';
    topics.forEach(function(t){t.allQuestions=t.questions.slice();t.questions=t.allQuestions.filter(matchesSource);});
    select.addEventListener('change',function(){state.sourceFilter=select.value;applyFilter();window.CafaPractice.refresh();renderCards();});
  }
  function mount(){if(mounted)return;mounted=true;mountFilter();var body=$('#oefenen .home-body'),core=$('#oefenen .topic-grid');core.insertAdjacentHTML('beforebegin','<h2 class="practice-section-title">Oefenen per deel</h2>');core.insertAdjacentHTML('afterend','<section class="practice-topics"><h2>Oefenen per onderwerp</h2><p>Gericht oefenen met dezelfde vragen en gedeelde voortgang. Kies uit 19 onderwerpen.</p><details class="topic-counting-rule"><summary>Hoe is de tentamenfrequentie geteld?</summary><p>Een onderwerp telt één keer per uniek tentamen als het expliciet wordt gevraagd of noodzakelijk is om een antwoord te bepalen, berekenen of boeken. Alleen achtergrondinformatie telt niet mee. Eén vraag kan meerdere onderwerpen toetsen; de aantallen kun je daarom niet optellen tot een examenweging.</p><p>11 tentamens: april en oktober 2021, april en oktober 2022, april en oktober 2023, april en september 2024, april en september 2025 en april 2026. Bij vaste-actieftransacties telt de levering onder vaste activa, niet automatisch als voorraadlevering.</p><p>Bij samengestelde onderwerpen telt aanwezigheid van een deelonderwerp mee; de frequentie betekent niet dat ieder deelonderwerp telkens is getoetst. Historische frequentie is een hulpmiddel voor oefenen, geen voorspelling van een volgend tentamen.</p><a href="tentamenfrequentie.html">Volledige telling en bronverwijzingen</a></details><div class="topic-groups" id="practice-topic-cards"></div></section>');
    var host=document.getElementById('app-content');topics.concat(Object.keys(window.CAFA2_DATA.modules).map(function(c){return get('deel-'+c);})).forEach(function(t){['overzicht','resultaat'].forEach(function(kind){var el=document.createElement('section');el.id='onderwerp-'+kind+'-'+t.id;el.className='screen frame topic-route';host.appendChild(el);});});
    // Append new rows to the existing four overviews, keeping every old question URL valid.
    Object.keys(window.CAFA2_DATA.modules).forEach(function(c){var bank=window.CAFA2_DATA.modules[c],list=$('#overzicht-'+c+' .overview-list');bank.questions.filter(function(q){return q.id>30;}).forEach(function(q){if(list)list.insertAdjacentHTML('beforeend','<a class="ov-item" data-nav="'+c+'-'+q.id+'" href="#'+c+'-'+q.id+'" title="'+esc(q.title)+'"><span class="ov-num">'+q.id+'</span><span class="ov-status">Niet beantwoord</span><span class="ov-mark" aria-label="Gemarkeerd">◇</span></a>');});var old=document.getElementById(c+'-30');if(old&&bank.questions.length>30){var a=$('.nav-left a:last-child',old);if(a)a.href='#'+c+'-31';}});
    Object.keys(window.CAFA2_DATA.modules).forEach(function(c){var bank=window.CAFA2_DATA.modules[c];bank.questions.forEach(function(q,i){var el=document.getElementById(c+'-'+q.id);if(!el)return;var nav=all('.nav-left a',el);if(nav[0])nav[0].href=i?'#'+c+'-'+bank.questions[i-1].id:'#overzicht-'+c;if(nav[1])nav[1].href=i+1<bank.questions.length?'#'+c+'-'+bank.questions[i+1].id:'#resultaat-'+c;});});
    var total=Object.values(window.CAFA2_DATA.modules).reduce(function(n,b){return n+b.questions.length;},0);$('.home-sub',$('#oefenen')).textContent='Vier delen · 19 onderwerpen · '+total+' oefenvragen';var badge=$('.cafa-home-choice.practice .cafa-choice-count');if(badge)badge.textContent=total+' vragen · vier delen en 19 onderwerpen';
    renderCards();route();
  }
  document.addEventListener('click',function(e){if(!mounted)return;var link=e.target.closest('a,button');if(!link)return;if(link.matches('.topic-exam-toggle')){var codes=document.getElementById(link.getAttribute('aria-controls')),expanded=link.getAttribute('aria-expanded')!=='true';link.setAttribute('aria-expanded',String(expanded));codes.hidden=!expanded;return;}var t=get(state.active);if(link.matches('[data-start]')){if(state.sourceFilter&&state.sourceFilter!=='all'){var part=get('deel-'+link.dataset.start);if(part.questions.length){e.preventDefault();e.stopImmediatePropagation();activate(part);location.hash=session(part).current;}else e.preventDefault();}else clear();return;}if(link.matches('[data-reset]')&&state.sourceFilter&&state.sourceFilter!=='all'){e.preventDefault();e.stopImmediatePropagation();reset(get('deel-'+link.dataset.reset));return;}if(link.dataset.topicReset){e.preventDefault();reset(get(link.dataset.topicReset));return;}if(link.dataset.topicFinish){e.preventDefault();finish(get(link.dataset.topicFinish));return;}if(link.matches('[data-overview]')&&!link.closest('.question')&&state.sourceFilter&&state.sourceFilter!=='all'){e.preventDefault();e.stopImmediatePropagation();location.hash='onderwerp-overzicht-deel-'+link.dataset.overview;return;}if(t&&link.closest('.question')&&(link.matches('[data-overview]')||link.matches('.practice-finish'))){e.preventDefault();e.stopImmediatePropagation();if(link.matches('[data-overview]'))location.hash='onderwerp-overzicht-'+t.id;else finish(t);}},true);
  window.addEventListener('hashchange',route);
  window.addEventListener('cafa:practice-change',function(){if(mounted&&location.hash==='#oefenen')renderCards();});
  window.CafaTopics={context:context,mount:mount,paintScore:paintScore,resetForModule:function(c){topics.concat([get('deel-'+c)]).filter(function(t){return (t.allQuestions||t.questions).some(function(uid){return uid.startsWith(c+'-');});}).forEach(function(t){Object.keys(state.topics).filter(function(key){return key===t.id||key.startsWith(t.id+':');}).forEach(function(key){var previous=state.topics[key];state.topics[key]={current:null,exam:false,finished:false,started:false,history:previous.history||[]};});if(state.active===t.id)state.active=null;});save();},importState:function(value){state=value&&value.topics&&typeof value.topics==='object'?{active:null,topics:value.topics,sourceFilter:['all','syllabus','exam'].includes(value.sourceFilter)?value.sourceFilter:'all'}:{active:null,topics:{},sourceFilter:'all'};save();},getState:function(){return JSON.parse(JSON.stringify(state));},stats:stats,topics:topics};
})();
