(function(){
  'use strict';
  var root=document.documentElement;
  var routes=[].slice.call(document.querySelectorAll('[data-route]'));
  var lessons=[].slice.call(document.querySelectorAll('[data-lesson]')).map(function(el){return el.dataset.lesson;});
  var key='cafa2-summary-v1',state={font:16,done:{}};
  try{var saved=JSON.parse(localStorage.getItem(key)||'{}');if(saved&&typeof saved==='object'){state.font=Number(saved.font)||16;state.done=saved.done||{};}}catch(e){}
  root.classList.add('enhanced');
  function save(){try{localStorage.setItem(key,JSON.stringify(state));}catch(e){}}
  function toast(message){var el=document.querySelector('.toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(function(){el.classList.remove('show');},1800);}
  function showRoute(){var id=(location.hash||'#start').slice(1);if(!document.querySelector('[data-route="'+id+'"]'))id='start';routes.forEach(function(el){el.classList.toggle('active',el.dataset.route===id);});document.querySelectorAll('[data-side],[data-top]').forEach(function(link){var current=(link.dataset.side||link.dataset.top)===id;if(current)link.setAttribute('aria-current','page');else link.removeAttribute('aria-current');});document.body.classList.remove('menu-open');document.getElementById('menu-toggle').setAttribute('aria-expanded','false');document.getElementById('content').focus({preventScroll:true});window.scrollTo(0,0);}
  window.addEventListener('hashchange',showRoute);
  document.getElementById('menu-toggle').addEventListener('click',function(){var open=document.body.classList.toggle('menu-open');this.setAttribute('aria-expanded',String(open));});
  function updateProgress(){var count=lessons.filter(function(id){return !!state.done[id];}).length;document.querySelector('[data-progress-label]').textContent=count+' van '+lessons.length;document.querySelector('[data-progress-bar]').style.width=(count/lessons.length*100)+'%';document.querySelectorAll('[data-side]').forEach(function(link){link.classList.toggle('done',!!state.done[link.dataset.side]);});document.querySelectorAll('[data-lesson]').forEach(function(lesson){var button=lesson.querySelector('[data-complete]');if(!button)return;var done=!!state.done[lesson.dataset.lesson];button.classList.toggle('is-done',done);button.textContent=done?'Beheerst ✓':'Markeer als beheerst';});}
  document.querySelectorAll('[data-complete]').forEach(function(button){button.addEventListener('click',function(){var id=button.closest('[data-lesson]').dataset.lesson;state.done[id]=!state.done[id];save();updateProgress();toast(state.done[id]?'Les gemarkeerd als beheerst.':'Markering verwijderd.');});});
  function setFont(value,store){state.font=Math.max(14,Math.min(22,value));root.style.setProperty('--base',state.font+'px');if(store)save();}
  document.querySelectorAll('[data-font]').forEach(function(button){button.addEventListener('click',function(){var delta=Number(button.dataset.font);setFont(delta===0?16:state.font+delta,true);});});setFont(state.font,false);
  document.querySelectorAll('[data-tab]').forEach(function(button){button.addEventListener('click',function(){var name=button.dataset.tab;document.querySelectorAll('[data-tab]').forEach(function(b){b.setAttribute('aria-selected',String(b===button));});document.querySelectorAll('[data-panel]').forEach(function(panel){panel.hidden=panel.dataset.panel!==name;});});});
  var search=document.getElementById('term-search');search.addEventListener('input',function(){var query=search.value.trim().toLowerCase(),shown=0;document.querySelectorAll('#terms article').forEach(function(card){var hit=!query||(card.dataset.term+' '+card.textContent).toLowerCase().indexOf(query)!==-1;card.hidden=!hit;if(hit)shown++;});document.querySelector('.empty').hidden=shown!==0;});
  function val(id){return Math.max(0,Number(document.getElementById(id).value)||0);}function money(n){return new Intl.NumberFormat('nl-NL',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(n);}
  function calculate(){var stream=document.getElementById('ic-stream').value,basis=document.getElementById('ic-basis').value,interest=Math.min(100,val('ic-interest'))/100,sales=val('ic-sales'),cost=val('ic-cost'),stock=val('ic-stock'),opening=val('ic-opening'),tax=Math.min(100,val('ic-tax'))/100,margin=sales?(sales-cost)/sales:0,closing=Math.max(0,stock*margin),delta=closing-opening,net=Math.abs(delta)*(1-tax),parentShare=stream==='down'?1:interest,minorityShare=1-parentShare,parent=net*parentShare,minority=net*minorityShare,separate=basis==='nvw'?net*interest:0,direction=delta>0?'lager':delta<0?'hoger':'ongewijzigd';document.querySelector('[data-result=closing]').textContent=money(closing);document.querySelector('[data-result=delta]').textContent=(delta<0?'− ':'')+money(Math.abs(delta));document.querySelector('[data-result=net]').textContent=money(net)+' '+direction;document.querySelector('[data-result=parent]').textContent=money(parent);document.querySelector('[data-result=minority]').textContent=money(minority);document.querySelector('[data-result=separate]').textContent=money(separate);document.querySelector('[data-parent-bar]').style.width=(parentShare*100)+'%';document.querySelector('[data-minority-bar]').style.width=(minorityShare*100)+'%';var seller=stream==='down'?'de moeder':stream==='up'?'de dochter':'de verkopende dochter';document.querySelector('[data-explain]').textContent='De winst is geboekt door '+seller+'. Daarom komt '+Math.round(parentShare*100)+'% van het netto effect bij de moeder en '+Math.round(minorityShare*100)+'% bij derden. '+(basis==='nvw'?'Bij NVW is '+money(separate)+' in de enkelvoudige moederkolom verwerkt.':'Bij verkrijgingsprijs is geen NVW-correctie vooraf geboekt.');var box=document.querySelector('[data-journal]');if(delta>0)box.innerHTML='<b>Bij toename:</b> verlaag de voorraad met '+money(delta)+', neem een belastinglatentie op van '+money(delta*tax)+' en verlaag het groepsresultaat netto met '+money(net)+'. Elimineer daarnaast de IC-omzet van '+money(sales)+'.';else if(delta<0)box.innerHTML='<b>Bij afname:</b> laat '+money(Math.abs(delta))+' van de eerdere voorraadcorrectie vrij. De belastinglatentie daalt met '+money(Math.abs(delta)*tax)+' en het groepsresultaat stijgt netto met '+money(net)+'.';else box.innerHTML='<b>Bij een gelijke ICW:</b> er is geen netto resultaateffect uit de mutatie. De eindvoorraad blijft met '+money(closing)+' gecorrigeerd.';}
  document.querySelectorAll('#ic-lab input,#ic-lab select').forEach(function(input){input.addEventListener('input',calculate);input.addEventListener('change',calculate);});document.querySelector('[data-reset]').addEventListener('click',function(){document.getElementById('ic-stream').value='down';document.getElementById('ic-basis').value='nvw';document.getElementById('ic-interest').value=80;document.getElementById('ic-sales').value=1200000;document.getElementById('ic-cost').value=1000000;document.getElementById('ic-stock').value=300000;document.getElementById('ic-opening').value=0;document.getElementById('ic-tax').value=25;calculate();});
  updateProgress();calculate();showRoute();
})();
