// Recognition guidance is derived from the asked task and its existing course context.
// Do not read the correct option: recognition must explain the question, not disclose its answer.
export function questionPattern(q){
 const task=String(q.task||q.prompt||''),t=task.toLowerCase(),topic=q.topicId||q.guidance?.lesson||'',kind=q.answerKind||q.type||'';
 const stock=kind==='stock'||kind==='Voorraadtabel',journal=kind==='journal'||kind==='Journaalpost'||/journaalpost|eliminatieboeking|correctieboeking|eliminatiepost/.test(t);
 const subject=/goodwill|badwill/.test(t)?'goodwill':/wettelijke reserve|herwaarderingsreserve/.test(t)?'de gebonden reserve':/aandeel derden|belang derden/.test(t)?'het aandeel van derden':/koersverschil|omrekeningsverschil/.test(t)?'het valuta- of omrekeningsverschil':/geconsolideerd.{0,20}resultaat/.test(t)?'het geconsolideerde resultaat':/boekwaarde|waarderen|waardeert|waardering/.test(t)?'de waardering of boekwaarde':/dividend/.test(t)?'dividend':/resultaat deelneming|resultaat uit deelneming/.test(t)?'het resultaat uit deelneming':/intercompany|onderlinge levering|intracomptabel/.test(t)?'de interne transactie':/stemrecht|dochter|kwalifice|kapitaalbelang/.test(t)?'de aard van het kapitaalbelang':'het gevraagde onderwerp';
 const scope=/enkelvoudig|intracomptabel/.test(t)?'in de enkelvoudige jaarrekening':/geconsolideerde winst|winst.en.verlies|w&v/.test(t)?'in de geconsolideerde winst-en-verliesrekening':/geconsolideerde?\s*balans/.test(t)?'in de geconsolideerde balans':/geconsolideer|eliminatie/.test(t)?'bij de consolidatie':'';
 let recognize=stock?'Een voorraadtabel vraagt om het verband tussen beginvoorraad, eindvoorraad, niet-gerealiseerde winst en de verdeling van de correctie.':journal?`De gevraagde journaalpost of eliminatieboeking verwerkt ${subject}${scope?' '+scope:''}. Herken eerst welke gebeurtenis of correctie moet worden geboekt.`:/functionele valuta|tijdstipmethode|slotkoersmethode/.test(t)&&/welke|mot|beredeneer|definitie/.test(t)?'Deze vraag vraagt om herkenning van de functionele valuta of de passende omrekeningsmethode. De economische omstandigheden bepalen de keuze.':/consolidatiekring|consolide|consolidatieplicht/.test(t)&&/welke|mot|beredeneer/.test(t)?'Herken twee afzonderlijke beslissingen: wie een geconsolideerde jaarrekening opstelt en welke ondernemingen daarin worden opgenomen. Beantwoord de beslissing die hier wordt gevraagd.':/kwalifice|dochtermaatschappij|wettelijke criteria/.test(t)?'Dit is een kwalificatievraag: je moet een casusfeit koppelen aan het juiste criterium voor de relatie tussen de ondernemingen.':/mot|beredeneer|waarom|grondslag/.test(t)?`Dit is een motiveringsvraag over ${subject}: de conclusie moet voortkomen uit een casusgegeven en de bijbehorende regel.`:`Dit is een berekenings- of verwerkingsvraag over ${subject}. Onderscheid de gevraagde eindstand van een mutatie of resultaat over het jaar.`;
 let watch;
 if(stock||/intercompany|onderlinge levering|intracomptabel|voorraad/.test(t)&&/^consolidatie|downstream|upstream|sidestream/.test(topic))watch='Bepaal wie levert aan wie, waar de voorraad ligt en welk belang moeder in leverancier en afnemer heeft. Gebruik de winstopslag of marge met de juiste noemer. Houd beginstand, eindstand en toe- of afname apart; pas de gegeven waarderingsgrondslag en winstbelasting toe.';
 else if(/goodwill/.test(t))watch='Houd verwervingsdatum, betaald bedrag, aandeel in het relevante eigen vermogen en afschrijvingstermijn uit elkaar. Bepaal of de vraag de goodwill bij aankoop, jaarlijkse afschrijving of een cumulatieve balanscorrectie vraagt.';
 else if(/wettelijke reserve|herwaarderingsreserve|reserve deelneming/.test(t))watch='Kijk naar de oorzaak en het tijdvak van de reserve: resultaten sinds de eerste waardering, uitkeringen, uitkeerbaarheid of herwaardering. Een resultaat van één jaar is niet vanzelf het bedrag van de reserve.';
 else if(/dividend/.test(t))watch='Bepaal wie het dividend betaalt en ontvangt, op welk belang het bedrag betrekking heeft en of het dividend al in de boekwaarde of het resultaat is verwerkt. De waarderingsgrondslag bepaalt of dividend de deelneming vermindert of een opbrengst vormt.';
 else if(/val|tijdstip|slotkoers|functionele/.test(topic)||/valuta|koersverschil|omrekeningsverschil|euro/.test(t)&&(q.code||q._code)==='val')watch='Herken de voorgeschreven omrekeningsmethode. Onderscheid monetaire posten, historische aanschafbedragen, transacties en resultaten. Koppel elk bedrag aan de passende historische, transactie-, gemiddelde of slotkoers en houd valutaresultaat en reserve gescheiden.';
 else if(/kwalifice|dochter|stemrecht|wettelijke criteria/.test(t)||topic==='zeggenschap')watch='Tel stemrechten apart van winstrechten. Let op aandelen zonder stemrecht, eigen aandelen, stemrechtovereenkomsten en benoemingsmacht. Controleer ook de rechtsvorm: een natuurlijke persoon is geen moederrechtspersoon; bij een v.o.f. kan volledige aansprakelijkheid beslissend zijn. Pas alleen een criterium toe waarvoor de casus gegevens geeft.';
 else if(topic==='consolidatiekader'||/consolidatiekring|consolidatieplicht/.test(t))watch='Onderscheid groepshoofd, groepsdeelhoofd en de ondernemingen waarover zeggenschap bestaat. Let op indirecte belangen, gezamenlijke zeggenschap en expliciete vrijstellingen; aandelenbezit alleen beslist niet elke consolidatievraag.';
 else if(/geconsolideerd.{0,20}resultaat|geconsolideerde winst/.test(t))watch='Begin met het resultaat van de moeder en herken welke dochterresultaten daarin al via de deelnemingswaardering zitten. Controleer het aandeel van derden, goodwillafschrijving en eventuele intercompany- en belastingcorrecties. Voorkom dat een al verwerkte mutatie nogmaals meetelt.';
 else if(/machine|inpak|vaste activ|inventaris|gebouw/.test(t)&&(/nvw|hk/.test(q.code||q._code||'')||topic==='vaste-activa'))watch='Herken een overdracht van een vast actief binnen de groep. Bepaal de interne boekwinst, verkoopdatum, oorspronkelijke boekwaarde en resterende afschrijvingstermijn. Onderscheid eliminatie van de boekwinst van de latere afschrijvingscorrectie en bepaal welke periode wordt gevraagd.';
 else if(/aandeel derden|belang derden/.test(t))watch='Gebruik het percentage van de derden en het juiste eigen vermogen of resultaat van de dochter. Controleer of eerdere consolidatiecorrecties en winstbelasting eerst moeten worden verwerkt en of de vraag een balansbedrag of jaarresultaat verlangt.';
 else if(journal)watch='Bepaal welke rekening toeneemt of afneemt en vanuit welke onderneming wordt geboekt. Zoek de waarderingsgrondslag, het belang en het tijdstip in de casus. Een eliminatie verwijdert een interne post; een enkelvoudige boeking verwerkt de gebeurtenis bij de onderneming zelf.';
 else watch='Zoek het gevraagde tijdstip en de waarderingsgrondslag. Houd aanschafprijs, aandeel in eigen vermogen, resultaat en uitkering uit elkaar. Neem uitsluitend mutaties mee die bij de gevraagde periode en onderneming horen.';
 const dates=[...new Set(task.match(/\b\d{1,2}[-/]\d{1,2}[-/]\d{4}\b|\b\d{1,2} (?:januari|februari|maart|april|mei|juni|juli|augustus|september|oktober|november|december) \d{4}\b/g)||[])];
 if(dates.length)watch+=' Gevraagd tijdstip: '+dates.join(' en ')+'.';
 let format=stock?'Vul de gevraagde rijen en kolommen in. Laat zien hoe de niet-gerealiseerde winst aansluit op interne correctie, aandeel derden en geconsolideerd resultaat.':journal?'Geef per boeking de rekeningnamen, debet- en creditbedragen en zo nodig een toelichting. Gebruik afzonderlijke boekingen voor afzonderlijke gebeurtenissen; debet en credit moeten per boeking aansluiten.':/mot|beredeneer|waarom|kwalifice|welke/.test(t)?'Geef de conclusie, het beslissende casusfeit en het toepasselijke criterium. Voeg een berekening of bronregel toe wanneer de vraag dat vraagt.':'Toon de relevante beginstand of formule, de ingevulde gegevens en de berekening tot de gevraagde uitkomst. Vermeld valuta of eenheid en geef bij een verschil ook het teken en de verwerking aan.';
 if(q.part)format+=` Beantwoord hier alleen onderdeel ${q.part}; gebruik benodigde eerdere uitkomsten als gegeven.`;
 return ['Herken de vraag: '+recognize,'Let op de beslissende gegevens: '+watch,'Vorm van het antwoord: '+format];
}
export function applyQuestionPattern(q){const pattern=questionPattern(q);q.guidance={...q.guidance,pattern};q.pattern=pattern.join(' ');return q;}
