import kap from './kap.mjs';
import val from './val.mjs';
import cons from './cons.mjs';
import {table as T,journal as J,example as E,note as N} from './helpers.mjs';
function add(list,id,html,refs=[]){const l=list.find(x=>x.id===id);if(!l)throw Error('Ontbrekend hoofdstuk '+id);l.html+=html;l.sources.push(...refs);}
add(kap,'stelselwijziging','<h3>Beleggingen: effecten en actuele-waardemutaties</h3><p>De syllabus plaatst duurzame beleggingen onder financiële vaste activa, post effecten, en niet-duurzame beleggingen onder vlottende activa, post effecten. Zij gebruikt een jaar als praktische tijdsafbakening. Voor de waardering geldt artikel 2:384 lid 1: verkrijgingsprijs of toepasselijke actuele waarde. De presentatie als vast of vlottend actief is dus een andere keuze dan de waarderingsgrondslag.</p><p>Artikel 2:384 lid 7 staat in de behandelde situatie toe actuele-waardeveranderingen rechtstreeks in het resultaat op te nemen. De syllabus wijst vervolgens op artikel 2:390 lid 1: dit betekent niet automatisch dat geen herwaarderingsreserve nodig is. Bij frequente marktnoteringen, bijvoorbeeld een beursnotering, noemt zij een uitzondering op die reservevorming.</p>'+E('Belegging van € 100.000 naar € 110.000; toepassing van art. 2:384 lid 7',J('Actuele waardestijging via het resultaat',[['0.. Effecten',10000,''],['9.. Aan Resultaat effecten','',10000]])+J('Aanvullende reserve wanneer de beschreven uitzondering niet geldt',[['0.. Overige reserves',10000,''],['0.. Aan Herwaarderingsreserve','',10000]])+'<p>Bij realisatie valt een gevormde reserve volgens deze syllabus vrij via dezelfde vermogensroute als waarlangs zij is gevormd. De tweede boeking is geen extra last in de winst-en-verliesrekening.</p>'),['S1|§9, p. 27–28; art. 2:384 leden 1 en 7 en 2:390 lid 1 BW']);
add(kap,'consolidatieplicht','<h3>Vrijstellingen concreet nalopen</h3>'+T(['Bepaling','Vereiste volgens de aangeleverde syllabus'],[
['Art. 2:407 lid 2 onderdelen a–c','Bij consolidatie worden de grenzen van art. 2:396 niet overschreden; geen betrokken maatschappij heeft de bedoelde effecten op een gereglementeerde markt, MTF of vergelijkbaar systeem; binnen zes maanden na begin boekjaar heeft niet ten minste 10% van de leden of het geplaatste kapitaal schriftelijk bezwaar gemaakt.'],
['Art. 2:407 lid 3','Uitsluitend beheer en financiering van groepsmaatschappijen en deelnemingen, beheer krachtens samenwerking met een niet in de eigen consolidatie opgenomen rechtspersoon, en toepassing van art. 2:389 in de eigen balans. Het betreft het buiten de consolidatie houden van de eigen gegevens, niet zomaar de gehele groep.'],
['Art. 2:408 lid 1 onderdeel a','Geen tijdig schriftelijk bezwaar binnen zes maanden na begin boekjaar door ten minste 10% van de leden of het geplaatste kapitaal.'],
['Art. 2:408 lid 1 onderdeel b','Alle financiële gegevens die de tussenhoudster zou moeten consolideren, zijn opgenomen in de geconsolideerde jaarrekening van het grotere geheel.'],
['Art. 2:408 lid 1 onderdeel c','De geconsolideerde jaarrekening en het bijbehorende verslag voldoen aan de in de aangeleverde tekst genoemde Europese voorschriften of zijn op gelijkwaardige wijze opgesteld.'],
['Art. 2:408 lid 1 onderdeel d','De geconsolideerde jaarrekening, accountantsverklaring en het verslag zijn in het Nederlands of vertaald naar Frans, Duits of Engels, in dezelfde taal.'],
['Art. 2:408 lid 1 onderdeel e','De vereiste stukken of de toegestane verwijzing zijn binnen zes maanden na balansdatum of binnen een maand na een geoorloofde latere openbaarmaking bij het handelsregister neergelegd.'],
['Art. 2:408 leden 3–4','Vermeld het gebruik in de toelichting; de vrijstelling geldt niet voor de in lid 4 beschreven rechtspersoon met effecten op de bedoelde gereglementeerde markt.']])+
N('RJ-beperkingen uit de syllabus','RJ 217.214 sluit toepassing van artikel 2:408 uit wanneer de betrokken gegevens uitsluitend proportioneel in het grotere geheel zijn opgenomen. RJ 217.304–305 behandelt de uitzonderlijke toepassing van artikel 2:407 lid 1. Een al geconsolideerde deelneming die later zal worden verkocht, blijft in beginsel geconsolideerd tot daadwerkelijke afstoting of tot zij om een andere reden niet meer tot de kring behoort.')+
'<p>Voor het uitsluitend aanhouden ter vervreemding noemt de syllabus onder RJ 217.305: verkoop binnen een jaar is waarschijnlijk, de maatschappij is onmiddellijk verkoopbaar, er ligt een verkoopbesluit en -plan, de uitvoering is gestart, de prijs past bij de reële waarde en een fundamentele wijziging of intrekking van het plan wordt niet verwacht. Gebruik de meegeleverde studiewettekst en deze bronvoorwaarden; deze samenvatting is geen externe actualisering daarvan.</p>', ['S1|§11.3, p. 34–36; art. 2:407–408 BW; RJ 217.214 en 217.304–305']);
add(val,'tijdstipmethode',E('Verkoop van een historisch gewaardeerd actief','<p>Een actief heeft op het verkoopmoment een buitenlandse boekwaarde van USD 80.000, met historische koers € 0,910. De verkoopopbrengst is USD 81.000 en de verkoopkoers € 0,912. Euroboekwaarde: € 72.800. Euroopbrengst: € 73.872. De boekwinst in euro’s is € 1.072. Alleen het buitenlandse verschil van USD 1.000 tegen één koers omrekenen geeft niet hetzelfde resultaat.</p>'),['S2|§4.1, p. 8–9: historische actiefwaarde en transactiekoers van opbrengsten']);
add(cons,'consolidatie-hk','<h3>Het 100%-geval als afzonderlijke controle</h3><p>Bij 100% vervallen de regels voor belang derden en aandeel derden. Stel dat de moeder € 120 betaalt voor een dochter met eigen vermogen van € 100 bij verwerving, goodwill € 20 en een afschrijvingstermijn van tien jaar. In het eerste volledige jaar maakt de dochter € 50 winst; de moeder heeft geen overige resultaatposten en ontvangt geen dividend.</p>'+J('Balans: verwerving',[['Eigen vermogen dochter bij verwerving',100,''],['Goodwill',20,''],['Aan Deelneming','',120]])+J('Balans: goodwillafschrijving eerste jaar',[['Resultaat boekjaar',2,''],['Aan Goodwill','',2]])+J('W&V: goodwillafschrijving eerste jaar',[['Afschrijvingskosten goodwill',2,''],['Aan Resultaat na belastingen','',2]])+'<p>De geconsolideerde jaarwinst is € 50 − € 2 = € 48. De winstgroei van de dochter sinds verkrijging blijft in de geconsolideerde vermogensontwikkeling zichtbaar; elimineer niet ten onrechte het volledige latere eigen vermogen tegenover de ongewijzigde verkrijgingsprijs.</p>', ['C8HK|dia 5–6: 100%-deelneming met goodwill']);
