import {lesson as L,table as T,journal as J,example as E,note as N,flow as F,money} from './helpers.mjs';
import {icScenario} from '../../js/ic-learning-engine.mjs';
function worked(title,input){const s=icScenario(input);return E(title,'<p>Eigen oefenvariant op de vermelde bronsystematiek. Alle voorraadtabelbedragen zijn vóór belasting. De getoonde boekingen gebruiken '+money(100*s.input.tax)+'% winstbelasting. Voorraadbedragen luiden tegen onderlinge verkoopprijs; de marge is '+money(100*s.input.margin)+'% van die verkoopprijs. Onderlinge leveringen in het boekjaar: € '+money(s.input.sales)+'.</p><div class="ic-stock-table">'+T(s.headers,s.rows,'Ingevulde voorraadtabel: '+s.variant+' '+s.input.basis)+'</div>'+N('Veronderstelde volgorde van de basiseliminaties',s.precondition)+'<h3>Stap 1. Interne correctie in de administratie van M</h3>'+(s.internal.some(j=>j.rows.length)?s.internal.filter(j=>j.rows.length).map(j=>J(j.title,j.rows)).join(''):'<p>Geen interne IC-winstboeking bij deze grondslag of geen winstmutatie.</p>')+'<h3>Stap 2. Geconsolideerde balans</h3>'+s.balance.filter(j=>j.rows.length).map(j=>J(j.title,j.rows)).join('')+'<h3>Stap 3. Geconsolideerde winst-en-verliesrekening</h3>'+s.income.filter(j=>j.rows.length).map(j=>J(j.title,j.rows)).join('')+'<h3>Stap 4. Controle</h3>'+T(['Controle','Bedrag (€)'],[['Volledige winst uit de eindvoorraad',s.controls.stockReduction],['Reeds intern verwerkte resultaatmutatie',s.controls.internalResultChange],['Aanvullende mutatie meerderheidsresultaat',s.controls.additionalMajorityResultChange],['Mutatie aandeel derden',s.controls.thirdResultChange]])+'<p class="source-note">'+s.source+'</p>');}
const nvwd={basis:'NVW',direction:'down',buyerShare:.6,stock0:320000,stock1:480000,margin:.2,tax:.25,sales:1200000};
const nvwu={basis:'NVW',direction:'up',sellerShare:.75,stock0:160000,stock1:240000,margin:.25,tax:.25,sales:1200000};
const nab={basis:'NVW',direction:'side',sellerShare:.7,buyerShare:.9,stock0:200000,stock1:260000,margin:.2,tax:.25,sales:900000};
const ab={basis:'NVW',direction:'side',sellerShare:.9,buyerShare:.7,stock0:300000,stock1:400000,margin:.3,tax:.2,sales:900000};
export default [
L('proces','nvw','Consolidatieproces: eerst de werkstaat bepalen','Consolideren gebeurt extracomptabel: de financiële gegevens van de betrokken ondernemingen worden buiten hun gewone administratie samengevoegd en gecorrigeerd.',
F(['Bepaal consolidatieplicht, kring en methode.','Breng gegevens op de juiste grondslagen en valuta.','Maak zo nodig interne correcties in de enkelvoudige administratie.','Stel balans- en W&V-consolidatie afzonderlijk op.','Elimineer relaties en verdeel het resultaat over meerderheid en derden.'])+
T(['Werklaag','Wat gebeurt hier?','Rekeningen'],[['Enkelvoudige administratie','Aankoop, resultaat, dividend en bij NVW de toepasselijke interne correcties.','Een journaalpost mag balans- en resultaatrekeningen combineren.'],['Geconsolideerde balans','Activa en verplichtingen op einddatum, eliminatie deelneming en eigen vermogen, belang derden, voorraadwinst en latenties.','In de syllabus bevat een balanseliminatie uitsluitend balansposten.'],['Geconsolideerde W&V','Baten en lasten van het jaar, onderlinge omzet en kosten, resultaat deelnemingen, goodwilllast en winsttoerekening.','In de syllabus bevat een W&V-eliminatie uitsluitend resultaatposten.']])+
N('Resultaat boekjaar versus resultaat na belastingen','Resultaat boekjaar is in een balanswerkstaat een component van het eigen vermogen. Resultaat na belastingen is in de afzonderlijke W&V-werkstaat een resultaatregel. Daardoor kunnen de uitwerkingen tegenboekingen gebruiken die afwijken van een gewone gecombineerde financiële journaalpost.'),
['S3|§2.1–2.2, p. 5–6; art. 2:405–406 BW zoals behandeld in S1 §11','A3|Lok, p. 4–5; Meppelt, p. 6–7']),
L('onderlinge-posten','nvw','De zes terugkerende eliminaties','Controleer de consolidatie systematisch. Niet iedere onderlinge post bevat ongerealiseerde winst.',
T(['Relatie','Balanseliminatie','W&V-eliminatie'],[
['Deelneming en eigen vermogen','Deelneming tegenover de vermogenscomponenten van de deelneming, met belang derden.','Resultaat deelnemingen en de winsttoerekening corrigeren.'],
['Onderlinge vordering en schuld','Dezelfde interne claim aan beide kanten verwijderen.','Bijbehorende rente elimineren.'],
['Voorraadwinst','Ongerealiseerde eindwinst uit voorraad, met de passende tegenposten en latentie.','Winstmutatie van het boekjaar verwerken.'],
['Managementfee','Eventuele nog openstaande interne schuld en vordering verwijderen.','Opbrengst managementfee tegenover managementkosten.'],
['Huur en rente','Openstaande onderlinge saldi verwijderen.','Interne huuropbrengst en huurlast, of rentebaten en rentelasten tegen elkaar.'],
['Goederenleveringen','Eindvoorraad alleen corrigeren voor ongerealiseerde winst.','Onderlinge omzet en kostprijs verwijderen; aanvullend de winstmutatie.']])+
E('Fee € 50.000 en rekening-courant € 75.000 bij integrale consolidatie',J('Balans',[['Rekening-courantschuld',75000,''],['Aan Rekening-courantvordering','',75000]])+J('W&V',[['Opbrengst managementfee',50000,''],['Aan Managementkosten','',50000]]))+
N('Integrale opname niet vermengen met percentages','Een 80%-dochter wordt integraal voor 100% opgenomen. Onderlinge gelijke vorderingen en schulden of fees worden dus niet slechts voor 80% geëlimineerd. Proportionele consolidatie heeft een andere omvang en wordt afzonderlijk behandeld.'),
['S3|§2.2, p. 6','A3|Lok, vraag 1–2, p. 4; Meppelt, p. 6']),
L('consolidatie-nvw','nvw','Basisconsolidatie bij NVW: 100% en niet-100%','De moeder heeft haar aandeel in het resultaat en vermogen al via de deelneming verwerkt. De consolidatie moet dubbeltellingen verwijderen en eventueel derden afzonderlijk tonen.',
E('80%-deelneming zonder goodwill of IC-verschillen','<p>D heeft aandelenkapitaal € 100.000, overige reserves € 300.000 en resultaat boekjaar € 100.000. De deelneming bij M is € 400.000. Het gewone resultaat deelneming is € 80.000.</p>'+
J('Balans',[['Aandelenkapitaal D',100000,''],['Overige reserves D',300000,''],['Resultaat boekjaar D',100000,''],['Aan Deelneming D','',400000],['Aan Belang derden','',100000]])+
J('W&V',[['Resultaat deelneming D',80000,''],['Aandeel derden',20000,''],['Aan Resultaat na belastingen D','',100000]])+
'<p>Bij een 100%-belang vervalt de derdenregel: de deelneming is € 500.000 en het resultaat deelneming € 100.000. Dat is geen andere consolidatiemethode, maar dezelfde integrale consolidatie zonder minderheid.</p>')+
'<h3>Wanneer is moederresultaat gelijk aan meerderheidsresultaat?</h3><p>In de eenvoudige NVW-situatie zonder aanvullende groepscorrecties zijn het enkelvoudige moederresultaat en het geconsolideerde resultaat toekomend aan de meerderheid gelijk. Dit is geen universele regel. Bij downstream met een niet-100%-belang en sidestream afnemend belang kunnen aanvullende correcties nodig zijn. Goodwill, grondslagverschillen en de vraag welke correcties al geboekt zijn moeten eveneens worden gecontroleerd.</p>'+
N('Voorraadwinst vereist een samenhangende set','Bij upstream en sidestream gebruikt de syllabus een specifieke combinatie van basiseliminatie en IC-eliminatie. Elimineer niet op eigen initiatief zowel de volledige ongecorrigeerde deelneming als opnieuw de intern verlaagde deelneming. Zie het hoofdstuk Boekingsmethoden voor de aansluiting.'),
['S3|§3.1 en §4.1, p. 8–15 en 54–63; §4.2.2, p. 78–83','E24A|vraag 7–8, p. 4–5']),
L('consolidatie-hk','hk','Basisconsolidatie bij verkrijgingsprijs','Bij HK is de koopsom in de deelneming blijven staan. De consolidatie moet daarom de verwervingsbasis, de goodwill en de latere winsten zichtbaar verwerken.',
F(['Elimineer het moederdeel op de verkrijgingsbasis.','Presenteer belang derden op de einddatum.','Activeer en volg de afzonderlijke consolidatiegoodwill.','Elimineer regulier dividend in de W&V en verdeel het dochterresultaat.'])+
T(['Onderdeel','Moment/basis'],[['Moederdeel kapitaaleliminatie','Eigen vermogen bij verkrijging, gecorrigeerd voor de in de casus meegekochte uitkeringen en latere relevante veranderingen.'],['Belang derden','Aandeel in het eigen vermogen op consolidatiedatum.'],['Goodwillbalans','Oorspronkelijke goodwill minus cumulatieve afschrijving.'],['Goodwilllast','Alleen de afschrijving van het lopende boekjaar.'],['Dividendopbrengst','Het bedrag dat de moeder als regulier dividend heeft geboekt.'],['Aandeel derden','Minderheidsaandeel in het resultaat, daarna aangepast voor toepasselijke IC-mutaties.']])+
E('Haven houdt 75% van Duin: volledige basisset','<p>Verkrijging op 1 januari 2023: prijs € 735.000, goodwill € 90.000, eigen vermogen € 860.000 bestaande uit kapitaal € 200.000, agio € 60.000 en overige reserves € 600.000. In 2023 is € 40.000 meegekocht dividend uitgekeerd, waarvan Haven € 30.000 op de deelneming heeft afgeboekt. Eind 2024 heeft Duin kapitaal € 200.000, agio € 60.000, reserves € 720.000 en resultaat € 160.000. Goodwill wordt in vijf jaar afgeschreven. Haven heeft in 2024 € 36.000 regulier dividend verantwoord.</p>'+
J('Balans: moederdeel verkrijging',[['Aandelenkapitaal Duin',150000,''],['Agio Duin',45000,''],['Overige reserves Duin',420000,''],['Goodwill',90000,''],['Aan Deelneming Duin','',705000]])+
J('Balans: belang derden einddatum',[['Aandelenkapitaal Duin',50000,''],['Agio Duin',15000,''],['Overige reserves Duin',180000,''],['Resultaat boekjaar Duin',40000,''],['Aan Belang derden','',285000]])+
J('Balans: twee jaren goodwillafschrijving',[['Overige reserves',18000,''],['Resultaat boekjaar',18000,''],['Aan Goodwill','',36000]])+
J('W&V: regulier dividend',[['Opbrengst deelneming Duin',36000,''],['Aan Resultaat na belastingen','',36000]])+
J('W&V: aandeel derden',[['Aandeel derden',40000,''],['Aan Resultaat na belastingen','',40000]])+
J('W&V: afschrijving lopend jaar',[['Afschrijvingskosten goodwill',18000,''],['Aan Resultaat na belastingen','',18000]])+
'<p>Controle goodwill: € 90.000 − € 36.000 = € 54.000. Het ontvangen meegekochte dividend verlaagt de aankoopreserves en de deelneming, niet de oorspronkelijke goodwill.</p>')+
N('Verwervingen gedurende het jaar','Bij meerdere aankopen houdt iedere tranche de eigen verkrijgingsbasis. Geef afzonderlijk aan welk resultaat vóór verwerving in het lopende boekjaar is behaald en welke goodwillafschrijving volgens de casus wordt gevraagd. Gebruik niet voor alle tranches blind het gezamenlijke eindpercentage.'),
['S3|§5.1 en §6.1, p. 104–111 en 143–152','C8HK|dia 3 en 7–10','E24S|Hoza, p. 12–14','E25A|Orvelde, p. 13–15','E25S|SchierGlas, p. 12–14']),
L('streams','nvw','NVW/HK en alle goederenrichtingen vergelijken','Bepaal drie dingen afzonderlijk: de enkelvoudige waardering, de verkoper-koperroute en de toename of afname van ongerealiseerde winst.',
T(['Route en grondslag','Intern','Derden','Aanvullend meerderheid'],[
['Downstream NVW','Belang in koper','Geen','100% minus belang in koper'],
['Upstream NVW','Belang in verkoper','100% minus belang in verkoper','Geen'],
['Sidestream NVW, niet-afnemend','Belang in verkoper','100% minus belang in verkoper','Geen'],
['Sidestream NVW, afnemend','Belang in koper','100% minus belang in verkoper','Belang in verkoper minus belang in koper'],
['Downstream HK','Geen','Geen','100%'],
['Upstream HK','Geen','100% minus belang in verkoper','Belang in verkoper'],
['Sidestream HK, niet-afnemend (college-Excel)','Geen','100% minus belang in verkoper','Belang in verkoper']])+
'<p>De percentages hierboven verdelen de volledige IC-winst vóór belasting. De kolom “aanvullend meerderheid” is het gedeelte dat na de interne correctie nog ten laste van het geconsolideerde meerderheidsresultaat komt. Het is dus niet altijd hetzelfde als het totale economische moederdeel.</p>'+
N('Dezelfde uitkomst, andere weg','Bij NVW is een deel al in de enkelvoudige jaarrekening gecorrigeerd. Bij HK ontbreekt die interne correctie. Daarom kunnen de uiteindelijke groepsvoorraad en winsttoerekening gelijk zijn terwijl de benodigde consolidatieboekingen verschillen.')+
N('Bronafbakening','De aangeleverde syllabus werkt sidestream afnemend belang uit bij NVW. Het college-Excel bevat daarnaast een HK-uitwerking voor sidestream niet-afnemend belang. Voor HK-sidestream afnemend belang wordt hier geen nieuwe onbevestigde voorbeeldboeking toegevoegd. De interactieve rekentool meldt dit expliciet in plaats van een veronderstelde uitwerking als bronregel te tonen.'),
['S3|§4–6 en §8.1, p. 64–103, 153–185 en 214–238','XIC|Downstream, Upstream, Sidestream AB en NAB; tabelrijen en HK-kolommen per werkblad']),
L('voorraadtabel','nvw','De zeskoloms voorraadtabel','Dit is de vaste brug tussen casus, interne journaalposten en consolidatie. Een blanco tabel ondersteunt het zelf uitwerken; een ingevulde tabel verklaart daarna de boekingen.',
'<div class="ic-stock-table">'+T(['Datum','Voorraad','Niet-gerealiseerde intercompanywinst in voorraad','Interne correctie','Eliminatie t.l.v. aandeel derden','Eliminatie t.l.v. geconsolideerd resultaat'],[['Percentage','','100%','…%','…%','…%'],['31-12-2024','','','','',''],['31-12-2025','','','','',''],['Toe-/afname','','','','','']],'Leeg tentamensjabloon')+'</div>'+
T(['Regel of kolom','Waarvoor gebruik je die?'],[['Voorraad','Voorraad bij de koper, gewaardeerd tegen de onderlinge verkoopprijs; let op hoeveelheden versus geldbedragen.'],['100%-winst','Voorraad × winstfractie in de onderlinge verkoopprijs; bij een opslag op kostprijs eerst de fractie herleiden.'],['Beginregel','Basis voor de beginvoorraad-invoeging en de aansluiting met eerdere correcties.'],['Eindregel','Uitvoegen van ongerealiseerde winst uit de geconsolideerde eindbalans.'],['Mutatieregel','Interne resultaatcorrectie en winstmutatie in de geconsolideerde W&V.'],['Correctiekolommen','Verdeling in reeds intern verwerkt, aandeel derden en nog aanvullend meerderheidsdeel.']])+
E('Het door jou aangeleverde voorbeeld: Moderna naar ChargeIT','<p>Downstream NVW, belang 60%, marge 20% van de onderlinge verkoopprijs. De bedragen hieronder reproduceren de voorraadtabel uit jouw screenshot. Belasting is niet in deze tabel verwerkt.</p><div class="ic-stock-table">'+T(['Datum','Voorraad','IC-winst in voorraad','Interne correctie','Eliminatie derden','Aanvullend geconsolideerd resultaat'],[['Percentage','','100%','60%','n.v.t.','40%'],['31-12-2024',320000,64000,38400,'n.v.t.',25600],['31-12-2025',480000,96000,57600,'n.v.t.',38400],['Toename',160000,32000,19200,'n.v.t.',12800]])+'</div><p>De interne boeking gebruikt € 19.200 uit de mutatieregel. De balans gebruikt de eindwinst € 96.000 en de interne eindcorrectie € 57.600. De aanvullende resultaatcorrectie vóór belasting is € 12.800, niet de gehele eindstand € 38.400.</p>')+
N('Ontbrekende gegevens niet terugzoeken','Bij de herwerkte oefenvragen staat de relevante casustabel bij de vraag zelf. Wanneer de tabel het te berekenen antwoord is, worden de afgeleide winst- en percentagekolommen niet vooraf ingevuld.'),
['U|Voorraadtabel Moderna–ChargeIT: de in dit gesprek aangeleverde screenshots','S3|§4.2.1–4.3.2, p. 64–103','A3O|Prato, p. 17–19; Moers, p. 73–74']),
L('ic-boekingsmethoden','nvw','Boekingsmethoden en volgorde van eliminaties','Gebruik één samenhangende boekingsset. Dezelfde groepsuitkomst kan via verschillende tussenboekingen worden bereikt, maar de tussenstappen zijn niet willekeurig uitwisselbaar.',
T(['Aanpak voor W&V-goedereneliminatie','Eerste boeking','Tweede boeking'],[
['Syllabus bij voorraadtoename','Omzet aan kostprijs voor interne leveringen minus voorraadtoename tegen onderlinge prijs.','Omzet van de voorraadtoename verdelen over oorspronkelijke kostprijs, winstcorrecties en belasting.'],
['Collegepresentatie met volledige omzet','Volledige interne omzet aan kostprijs.','Alleen de winstmutatie via kostprijs en de passende correctierekeningen.'],
['Bij vrijval van winst','Onderlinge omzet afzonderlijk verwijderen.','Vrijval via credit kostprijs; de winst- en belastingdelen draaien om.']])+
E('Waarom € 900.000 en € 60.000 niet dubbel mogen worden geëlimineerd','<p>Onderlinge leveringen zijn € 900.000, voorraadtoename tegen onderlinge prijs € 60.000 en winst daarin € 12.000. De syllabus verdeelt dit in € 840.000 doorlevering en € 60.000 voorraadtoename. Een equivalente volledige-omzetpresentatie begint met € 900.000 en corrigeert daarna uitsluitend de winstmutatie van € 12.000. Eerst € 900.000 en daarna nog € 60.000 omzet verwijderen is dubbel.</p>')+
'<h3>Upstream en sidestream NVW: deelneming en resultaat aansluiten</h3><p>In de balansvoorbeelden van de syllabus wordt het dochtervermogen eerst geëlimineerd met een deelnemingsbedrag gebaseerd op het aandeel in het vermogen vóór IC-correctie. De IC-post debiteert daarna de intern gecorrigeerde deelneming voor het relevante netto deel. Samen verwijderen deze posten de werkelijk geboekte, lagere deelnemingswaarde.</p><p>In de W&V wordt eerst het werkelijk bij M geboekte resultaat deelnemingen geëlimineerd. Daardoor kan in de goedereneliminatie een tegenboeking op “Resultaat na belastingen verkoper” nodig zijn om het dochterresultaat te laten aansluiten. Een collegewerkblad kan bij een andere presentatie een rekening “Resultaat deelneming” tonen. Vervang die labels niet zonder de voorafgaande eliminatie mee te veranderen.</p>'+
E('Balanscontrole bij upstream: € 900.000 vóór IC','<p>Een 75%-aandeel in het dochtervermogen is € 900.000. De interne eindcorrectie is € 33.750 netto, zodat de deelneming werkelijk voor € 866.250 is geboekt. De syllabuscombinatie crediteert in de basiseliminatie € 900.000 en debiteert in de IC-post € 33.750. Per saldo wordt € 866.250 verwijderd. Wie eerst al slechts € 866.250 crediteert en vervolgens nog € 33.750 debiteert, laat ten onrechte een restsaldo staan.</p>')+
N('Rekeningnaam bij vrijval','De bronsets gebruiken bij downstreamvrijval zowel Gerealiseerde winst als een credit op Niet-gerealiseerde winst. De herwerkte oefenvraag benoemt welke rekening wordt gevraagd; het economische effect en de aansluitende consolidatieboeking moeten daarbij gelijk blijven.'),
['S3|p. 69–73, 78–83, 99–102 en 230–232','XIC|Downstream toename, rij 42–51; Upstream toename, W&V-kolommen; Sidestream AB, rij 44–54','E25S|SchierGlas, p. 12–14']),
L('downstream-nvw','nvw','Downstream bij NVW','M verkoopt aan D. M stelt intern haar deelnemingsdeel van de winst uit; de consolidatie corrigeert daarnaast het overige deel volledig bij de meerderheid.',
F(['Hulpberekening: zeskoloms voorraadtabel vóór belasting.','Stap 1: interne correctie via overlopende passiva en belasting.','Stap 2: eindwinst uit voorraad; aanvullend beginwinst invoegen.','Stap 3: omzet en winstmutatie in de W&V elimineren.','Stap 4: netto aanvullende resultaatmutatie controleren.'])+
'<p>Bij 100% deelname is de volledige winst al intern gecorrigeerd; de aanvullende meerderheidskolom is dan nihil. Bij een niet-100%-belang blijft een aanvullende consolidatiecorrectie nodig. Die wordt niet op derden afgewenteld, omdat de moeder de winst heeft gemaakt.</p>'+
worked('Toename: 60%-belang, voorraad € 320.000 naar € 480.000',nvwd)+
worked('Afname: dezelfde route, voorraad € 480.000 naar € 320.000',{...nvwd,stock0:480000,stock1:320000})+
N('Intra en consolidatie niet samenvoegen','De interne correctie behoort tot de enkelvoudige administratie van M. De latere consolidatie neemt de overlopende passiefpost terug en verlaagt de groepsvoorraad. Beide stappen zijn nodig; het is geen keuze tussen de ene of de andere.'),
['S3|§4.2.1 en §4.3.1, p. 64–73 en 85–94','XIC|Downstream toename en Downstream afname','E24A|consolidatie NVW, p. 9–12']),
L('upstream-nvw','nvw','Upstream bij NVW','D verkoopt aan M. Het interne moederdeel wordt na belasting verwerkt op resultaat deelneming en deelneming in de verkoper; derden dragen hun eigen deel.',
'<p>Voor de interne boeking wordt de winstmutatie gebruikt. Voor de eindwaarde van de deelneming en de geconsolideerde voorraad is de resterende eindwinst bepalend. Bij een 100%-deelneming vervalt het derdenaandeel; bij een niet-100%-deelneming blijft dat zichtbaar in balans en W&V. De combinatie van basiseliminatie en goederenpost moet aansluiten op de werkelijk geboekte deelneming.</p>'+
worked('Toename: 75%-belang en marge 25% in verkoopprijs',nvwu)+
worked('Afname: upstreamwinst komt vrij',{...nvwu,stock0:240000,stock1:160000})+
N('Geen downstream-invoeging overnemen','In de hier gebruikte upstream-NVW-verdeling is het aanvullende meerderheidsdeel nihil. Er is dus niet dezelfde aanvullende beginvoorraad-invoeging als bij downstream met een minder dan 100%-belang. Houd de basiseliminatie en de IC-post als één set aan.'),
['S3|§4.2.2 en §4.3.2, p. 74–84 en 95–103','XIC|Upstream toename en Upstream Afname','E25A|Kisjes, p. 10–12']),
L('sidestream','nvw','Sidestream: welke belangen zijn relevant?','De goederen gaan tussen deelnemingen. Het belang langs de goederenpijl en de voorraadmutatie zijn twee afzonderlijke dimensies.',
T(['Verkoper → koper','Naam','Interne correctie bij NVW'],[['M houdt 70% → M houdt 90%','Niet-afnemend belang.','70%: het belang in de verkoper.'],['M houdt 90% → M houdt 70%','Afnemend belang.','70%: het lagere belang in de koper, op de deelnemingsrekening van de verkoper.'],['M houdt 80% → M houdt 80%','Niet-afnemend / gelijk belang.','80%; geen aanvullend meerderheidsdeel.']])+
'<p>“Afnemend belang” betekent hier niet dat M gedurende het jaar aandelen verkoopt. Het vergelijkt de moederbelangen in de verkoper en de koper. Binnen beide typen kan de voorraad vervolgens toenemen of afnemen. De interne correctie wordt in de moederadministratie op de verkopende deelneming verwerkt, omdat daar de winst is ontstaan.</p>'+
N('Vermijd twee veelgemaakte verwisselingen','De voorraadrekening hoort bij de koper, maar resultaat deelneming en deelneming bij de interne correctie verwijzen naar de verkoper. Het derdenpercentage volgt eveneens de verkoper. Alleen het interne percentage kan bij afnemend belang door het lagere kopersbelang worden bepaald.'),
['S3|§8.1, p. 214–238','XIC|Sidestream AB en Sidestream NAB; let op de feitelijke percentages, niet uitsluitend de tekstlabels','E23A|Bruggeman, p. 6–7']),
L('sidestream-nab','nvw','Sidestream niet-afnemend belang bij NVW','De interne correctie volgt het moederdeel in de verkoper. Het resterende deel is voor derden; er is geen aanvullende meerderheidskolom.',
worked('70%-verkoper naar 90%-koper: voorraadtoename',nab)+
worked('70%-verkoper naar 90%-koper: voorraadafname',{...nab,stock0:260000,stock1:200000})+
N('Hoger kopersbelang niet doorrekenen','Een 90%-belang in de koper maakt het interne winstdeel niet 90%. De bronmethodiek volgt bij deze niet-afnemende route het 70%-belang in de verkoper. Bij een later andere route moet opnieuw worden getoetst.'),
['S3|§8.1.1, p. 214–226','XIC|Sidestream NAB toename en Sidestream NAB Afname','E23A|Bruggeman, p. 6–7']),
L('sidestream-ab','nvw','Sidestream afnemend belang bij NVW','Hier zijn alle drie de correctiekolommen relevant: intern volgens koper, derden volgens verkoper en het verschil aanvullend voor de meerderheid.',
worked('90%-verkoper naar 70%-koper: voorraadtoename',ab)+
worked('90%-verkoper naar 70%-koper: voorraadafname',{...ab,stock0:400000,stock1:300000})+
N('Beginwinst niet vergeten','De aanvullende eindwinst mag niet geheel als last van het lopende jaar blijven staan wanneer al een beginvoorraad aanwezig was. Daarom wordt het aanvullende netto deel van de beginwinst vanuit reserves ingevoegd. De resultaatsmutatie sluit dan aan op het verschil tussen eind- en beginwinst.'),
['S3|§8.1.2, p. 226–238, in het bijzonder p. 228 en 230–232','XIC|Sidestream AB toename en Sidestream AB afname']),
L('downstream-hk','hk','Downstream bij verkrijgingsprijs','Geen interne IC-correctie, geen derdenaandeel in de winst van M: de volledige correctie komt in de consolidatie bij de meerderheid.',
worked('Toename: HK, voorraad € 180.000 naar € 240.000',{basis:'HK',direction:'down',buyerShare:.75,stock0:180000,stock1:240000,margin:.2,tax:.2,sales:900000})+
worked('Afname: HK, voorraad € 240.000 naar € 180.000',{basis:'HK',direction:'down',buyerShare:.75,stock0:240000,stock1:180000,margin:.2,tax:.2,sales:900000})+
N('Het 75%-belang begrenst deze correctie niet','De winst is door M gemaakt. Bij HK wordt daarom 100% van de downstreamwinst gecorrigeerd bij consolidatie, ook al houdt M slechts 75% van de koper. Het gebruik van 75% zou een deel van de eigen winst van M onterecht gerealiseerd laten.'),
['S3|§6.2.1 en §6.3.1, p. 153–158 en 166–175','A3|Boit, p. 69–71','E25S|SchierGlas, p. 12–14']),
L('upstream-hk','hk','Upstream bij verkrijgingsprijs','De dochter is de verkoper. Zonder interne NVW-correctie wordt de volledige winst in de consolidatie verdeeld over meerderheid, derden en belasting.',
worked('Afname: 75%-verkoper, opslag 25% op kostprijs = marge 20% in verkoopprijs',{basis:'HK',direction:'up',sellerShare:.75,stock0:300000,stock1:240000,margin:.2,tax:.2,sales:900000})+
worked('Toename: dezelfde upstream-HK-verdeling',{basis:'HK',direction:'up',sellerShare:.75,stock0:240000,stock1:300000,margin:.2,tax:.2,sales:900000})+
N('Opslag omrekenen','25% opslag op kostprijs betekent winst 25 op verkoopprijs 125: de winstfractie is 20%. De voorraad staat bij de koper doorgaans tegen die onderlinge verkoopprijs. De eindwinst volledig uit voorraad halen en haar vervolgens verdelen zijn twee aparte berekeningen.'),
['S3|§6.2.2 en §6.3.2, p. 159–165 en 176–185','C8UP|dia 3–13','E24S|Hoza, p. 12–14','E25A|Orvelde, p. 13–15']),
L('mva','nvw','Intercompanyverkoop van een materieel vast actief','Een interne verkoop verandert niet de oorspronkelijke groepsboekwaarde. De winst wordt eerst uitgesteld en komt daarna vrij via de extra afschrijving bij de koper.',
F(['Bereken de boekwaarde direct vóór interne verkoop.','Bepaal interne verkoopwinst: verkoopprijs minus groepsboekwaarde.','Corrigeer de initiële winst volgens richting, aandeel en grondslag.','Bereken jaarlijks extra afschrijving bij de koper.','Volg resterende winst in de balans en vrijval in de W&V.'])+
E('Downstream NVW: machine verkocht voor € 90.000','<p>M bezit 80% van D. Oorspronkelijke aanschafprijs € 120.000, levensduur acht jaar, restwaarde nihil. Na vier jaar verkoopt M de machine voor € 90.000 aan D. Groepsboekwaarde € 60.000; interne winst € 30.000. D schrijft nog vier jaar af. Winstbelasting 25%.</p>'+
J('M: interne correctie in het verkoopjaar',[['9.. Niet-gerealiseerde boekwinst',24000,''],['1.. Aan Overlopende passiva','',24000]])+
J('M: belastingcorrectie',[['0.. Voorziening belastingen (debetcorrectie)',6000,''],['9.. Aan Belastinglast','',6000]])+
J('Balans op verkoopdatum',[['Overlopende passiva',24000,''],['Resultaat boekjaar',4500,''],['Voorziening belastingen (aanvullend)',1500,''],['Aan Machine','',30000]])+
'<p>In het volgende jaar schrijft D € 22.500 af, terwijl de groep € 15.000 zou afschrijven. De extra afschrijving is € 7.500. Daarmee daalt de resterende interne winst van € 30.000 naar € 22.500.</p>'+
J('M: interne vrijval in het volgende jaar',[['1.. Overlopende passiva',6000,''],['9.. Aan Gerealiseerde boekwinst','',6000]])+
J('M: belasting over de vrijval',[['9.. Belastinglast',1500,''],['0.. Aan Voorziening belastingen','',1500]])+
J('W&V: extra afschrijving na de interne vrijval',[['Gerealiseerde boekwinst',6000,''],['Resultaat na belastingen (aanvullend)',1125,''],['Belastinglast (aanvullend)',375,''],['Aan Afschrijvingskosten machine','',7500]])+
J('Balans volgend jaar: resterende winst',[['Overlopende passiva',18000,''],['Resultaat boekjaar',3375,''],['Voorziening belastingen (aanvullend)',1125,''],['Aan Machine','',22500]])+
J('Balans volgend jaar: aanvullende beginwinst invoegen',[['Overige reserves',4500,''],['Aan Resultaat boekjaar','',4500]]))+
E('Upstream NVW: boekwinst en extra afschrijving','<p>M houdt 70% van D. D verkoopt een machine met groepsboekwaarde € 500.000 voor € 600.000. De resterende levensduur is vijf jaar en belasting 25%. De winst van € 100.000 wordt verdeeld naar de verkoper: 70% intern en 30% derden. De interne correctie is € 52.500 na belasting.</p>'+
J('M: interne correctie',[['9.. Resultaat deelneming D',52500,''],['0.. Aan Deelneming D','',52500]])+
J('Balans: winst op verkoopdatum verwijderen',[['Deelneming D',52500,''],['Voorziening belastingen (intern)',17500,''],['Belang derden',22500,''],['Voorziening belastingen (derden)',7500,''],['Aan Machine','',100000]])+
'<p>De extra jaarlijkse afschrijving is € 20.000. De netto vrijval bedraagt € 15.000, waarvan € 10.500 voor M en € 4.500 voor derden. Na één jaar resteert € 80.000 interne winst in de machine; gebruik voor de balans die eindstand en voor het resultaat de vrijval van € 20.000.</p>'+
J('W&V: correctie extra afschrijving volgens de syllabusvolgorde',[['Resultaat na belastingen verkoper',10500,''],['Belastinglast (intern)',3500,''],['Aandeel derden',4500,''],['Belastinglast (derden)',1500,''],['Aan Afschrijvingskosten machine','',20000]]))+
N('Verkoopwinst versus resterende winst','In het verkoopjaar corrigeer je de boekwinst. In latere jaren corrigeer je de te hoge afschrijving en de resterende winst in het actief. De opgaven kunnen een andere timing of gebruiksduur geven; volg die expliciet.'),
['S3|§8.2, p. 239–248','A3|Smit, Alkmaar en Eiken, p. 97–104','E22O|Molina, p. 7–9']),
L('proportioneel','nvw','Proportionele consolidatie en joint ventures','Evenredige opname betekent dat niet alle posten voor 100% worden toegevoegd. Daardoor is er geen afzonderlijk belang of aandeel derden uit deze proportionele opname.',
T(['Onderdeel','Werkwijze'],[['Voorwaarden','Gezamenlijke uitoefening van de relevante rechten krachtens een regeling tot samenwerking en voldoen aan het wettelijke inzicht, art. 2:409 BW.'],['Opname','Activa, verplichtingen, baten en lasten naar het gehouden belang opnemen.'],['Deelneming en vermogen','Het opgenomen evenredige vermogen tegenover de deelneming elimineren.'],['Derden','Geen aparte derdenpost voor het niet in de cijfers opgenomen deel.'],['Interne relaties','Elimineren voor zover die in de combinatie zijn opgenomen; het niet-geconsolideerde deel kan blijven staan.'],['Keuze volgens het bronmateriaal','Waar art. 2:409 toepassing toestaat, behandelen de uitwerkingen zowel proportionele opname als verwerking als deelneming in de geconsolideerde jaarrekening.']])+
E('Meppelt en Oogveen: 50% proportioneel','<p>Meppelt heeft een vordering van € 200.000 op Oogveen; Oogveen een schuld van € 200.000 aan Meppelt. Slechts 50% van Oogveens schuld is in de consolidatiestaat opgenomen. De eliminatie bedraagt daarom € 100.000; de resterende vordering € 100.000 verdwijnt niet. Een managementfee van totaal € 60.000 wordt voor € 30.000 tegen de opgenomen kosten geëlimineerd.</p>'+
J('Rekening-courant',[['Rekening-courantschuld Oogveen',100000,''],['Aan Rekening-courantvordering Meppelt','',100000]])+
J('Managementfee',[['Opbrengst managementfee',30000,''],['Aan Managementkosten','',30000]]))+
'<h3>Voorraadwinst bij proportionele opname</h3><p>De integrale regel “100% winst uit de voorraad” mag niet zonder aanpassing naar proportionele consolidatie worden gekopieerd. De syllabus elimineert binnen de evenredig opgenomen relatie het betrokken aandeel. Bij 50% en een relevante winst van € 40.000 is dat € 20.000. Er is geen aanvullende derdenpost voor de buiten de consolidatie gebleven helft. Volg de exacte richting en opgenomen bedragen uit de opgave.</p>'+
N('Overgang naar integrale opname','Wanneer gezamenlijke zeggenschap plaatsmaakt voor beslissende zeggenschap en integrale consolidatie passend wordt, kan de gepresenteerde groepsomzet stijgen terwijl het aan de moeder toekomende resultaat bij gelijk economisch belang niet automatisch stijgt. De uitwerking Meppelt laat dat onderscheid expliciet zien.'),
['S1|§11.4, p. 36–37; art. 2:409 BW','S3|§7, p. 186–213','A3|Meppelt, p. 6–7; Runa, Mestlin en Mussel, p. 72–82','E24S|vraag 7–8, p. 6']),
L('resultaataansluiting','hk','Eindcontrole: voorraad, meerderheid en derden','Laat een consolidatie niet eindigen bij losse journaalposten. Controleer de totale voorraad en de aansluiting van enkelvoudig naar geconsolideerd resultaat.',
T(['Controle','NVW','HK'],[['Voorraad integraal','Som eindvoorraden minus volledige interne eindwinsten vóór belasting.','Dezelfde groepsvoorraadcontrole; geen interne correctie veronderstellen.'],['Meerderheidsresultaat','Begin bij het moederresultaat en bepaal welke correcties daarin al zitten; voeg alleen nog ontbrekende groepscorrecties toe.','Moederresultaat + winstaandelen dochters − geboekte reguliere dividenden − jaarafschrijving goodwill +/− relevante netto IC-mutaties.'],['Aandeel derden','Gewone minderheidswinst corrigeren voor netto winstmutaties bij de betrokken verkopende dochters.','Hetzelfde economische toerekeningsprincipe, maar andere voorafgaande boekingen.'],['Balans versus W&V','Eindwinst bepaalt de voorraadcorrectie; mutatie bepaalt het jaarresultaat.','Eindwinst uitvoeren en aanvullende beginwinst invoegen houden de jaarresultaatcorrectie zuiver.']])+
E('HK-eindcasus: Moer, Delta en Eko',T(['Gegeven','Delta → Moer (upstream)','Moer → Eko (downstream)'],[['Moederbelang','80% in Delta','70% in Eko'],['Winst beginvoorraad',50000,80000],['Winst eindvoorraad',70000,60000],['Mutatie winst',20000,-20000],['Winstbelasting','20%','20%']])+
'<p>Eindvoorraden: Moer € 410.000, Delta € 260.000 en Eko € 390.000. Resultaten na belasting: Moer € 500.000, Delta € 200.000 en Eko € 180.000. Moers resultaat bevat ontvangen reguliere dividenden van 80% × € 60.000 en 70% × € 40.000. Goodwilljaarafschrijving: € 12.000 en € 18.000, zonder belastingeffect.</p>'+
T(['Aansluiting meerderheidsresultaat','Bedrag (€)'],[['Moer + aandelen in dochterwinsten',786000],['Dividendopbrengsten verwijderen',-76000],['Goodwilljaarafschrijving',-30000],['Upstreamtoename: −80% × 20.000 × 80%',-12800],['Downstreamvrijval: +20.000 × 80%',16000],['Meerderheidsresultaat',683200]])+
'<p>Aandeel derden: 20% × (€ 200.000 − € 20.000 × 80%) + 30% × € 180.000 = € 90.800. Groepsresultaat vóór winsttoerekening: € 683.200 + € 90.800 = € 774.000. Geconsolideerde voorraad: € 1.060.000 − € 70.000 − € 60.000 = € 930.000.</p>')+
N('Geen dubbele interne correcties','De zin “alle interne correcties zijn al verwerkt” verandert wat nog moet worden gedaan. Bij NVW kan het opnieuw aftrekken van de interne winstmutatie de grootste fout in een resultaataansluiting zijn.'),
['S3|§4–6 en §8.1; controles bij de betrokken voorbeelden','A3|Boit, p. 69–71','E25A|Kisjes en Orvelde, p. 10–15','E25S|Oldemarcke en SchierGlas, p. 9–14'])
];
