export const sources={
OP:{file:'Onderwijsprogramma CAFA2_VJ 2026.pdf',note:'Doelstellingen p. 3; toetsmatrijs p. 4–5; collegeprogramma p. 5–7. De vier leerdoelen wegen 30%, 20%, 30% en 20% in het programma.'},
S1:{file:'2026 Syllabus CAFA2 Deel 1 Kapitaalbelangen.pdf',note:'Theoretisch kader kapitaalbelangen en consolideren; oorspronkelijke hoofdstukken 1–11, p. 4–37.'},
S2:{file:'2026 Syllabus CAFA2 Deel 2 Vreemde valuta.pdf',note:'Valutabegrippen, functionele valuta en beide omrekenmethoden. De verwijzingen gebruiken de PDF-paginanummers; de tekstextractie van enkele voetregels bevat extra nullen.'},
S3:{file:'2026 Syllabus CAFA2 Deel 3 Consolideren.pdf',note:'Consolidatieproces, NVW, verkrijgingsprijs, proportioneel, sidestream en materiële vaste activa; p. 5–248.'},
BW:{file:'Burgerlijk wetboek Boek 2.pdf',note:'Aangeleverde studieversie met art. 24a–24d en 360–414. De titel vermeldt gelding vanaf 1 januari 2025. Deze revisie actualiseert de wettekst niet op basis van externe bronnen.'},
A1O:{file:'2026 Syllabus CAFA2 deel 1a - opgaven kapitaalbelangen owp.pdf',note:'Opgaven van het onderwijsprogramma, waaronder Westerheuvel, Eiberg en Unischelp.'},
A1:{file:'2026 Syllabus CAFA2 deel 1a - uitwerking opgaven kapitaalbelangen owp.pdf',note:'Uitwerkingen bij de opgaven van het onderwijsprogramma.'},
A1BO:{file:'2026 Syllabus CAFA2 deel 1b - opgaven kapitaalbelangen extra.pdf',note:'Extra casussen, waaronder Fort, Manting en Purmer.'},
A1B:{file:'2026 Syllabus CAFA2 deel 1b - uitwerking opgaven kapitaalbelangen extra.pdf',note:'Uitwerkingen extra kapitaalbelangen; Fort p. 5, Manting p. 6, Purmer p. 7–9.'},
A2O:{file:'2026 Syllabus CAFA2 deel 2a - opgaven vreemde valuta owp.pdf',note:'Onder meer Wijo, Corona, Alberobello, Ultima Prova, Oostermoer en Boil.'},
A2:{file:'2026 Syllabus CAFA2 deel 2a - uitwerking opgaven vreemde valuta owp.pdf',note:'Uitwerkingen bij de valutacasuïstiek van het onderwijsprogramma.'},
A2BO:{file:'2026 Syllabus CAFA2 deel 2b - opgaven vreemde valuta extra.pdf',note:'Extra valutacasussen. Controleer de inhoud, niet uitsluitend de titelpagina: het aangeleverde opgavenbestand vermeldt op die pagina Uitwerkingenbundel.'},
A2B:{file:'2026 Syllabus CAFA2 deel 2b - uitwerking opgaven vreemde valuta extra.pdf',note:'Uitwerkingen van Boccalupo tot en met Brand, waaronder M&D p. 40–41.'},
A3O:{file:'2026 Syllabus CAFA2 deel 3a - opgaven consolidatie owp.pdf',note:'Alle 32 opgaven van het onderwijsprogramma; bevat de gevraagde voorraadtabelvorm, onder meer Prato p. 17–19.'},
A3:{file:'2026 Syllabus CAFA2 deel 3a - uitwerking opgaven consolidatie owp.pdf',note:'Uitwerkingen van Lok tot en met Eiken; aparte balans- en W&V-eliminaties.'},
A3BO:{file:'2026 Syllabus CAFA2 deel 3b - opgaven consolidatie extra.pdf',note:'Extra consolidatieopgaven. De bijbehorende uitwerkingenbundel was niet als lokaal beschikbaar bronbestand vastgesteld in deze revisie; deze opgaven vormen daarom geen zelfstandige geverifieerde antwoordbron.'},
C3:{file:'Slides College 3 2025 CAFA2 [copyright Nyenrode Business Universiteit].pptx',note:'Onder meer Unischelp dia 25–33 en valutabegrippen vanaf dia 35; tabellen en toelichtingen gebruikt naast de syllabus.'},
C8HK:{file:'Slides College 8 2025 CAFA2 [copyright Nyenrode Business Universiteit] 4. Consolidatie HK.pptx',note:'Aparte verkrijgingseliminatie, derden op einddatum en goodwillafschrijving; dia 3–10.'},
C8UP:{file:'Slides College 8 2025 CAFA2 [copyright Nyenrode Business Universiteit] 6. Upstream NVW HK.pptx',note:'De titelpagina en bestandsnaam verschillen; de getoonde uitwerking behandelt HK-upstream, toename en afname, dia 3–13.'},
XIC:{file:'CAFA2 8. Intercompany Journaaplosten.xlsx',note:'Werkbladen Downstream toename/afname, Upstream toename/Afname, Sidestream AB toename/afname en Sidestream NAB toename/Afname. De collegekolommen en syllabuskolommen mogen niet zonder controle worden gemengd.'},
E21O:{file:'2021-10 CAFA2 - Uitwerking tentamen.pdf',note:'6 oktober 2021; getoetst naast het aangeleverde tentamen. Onder meer Ahorn/Finken en Modena.'},
E22A:{file:'2022-04 CAFA2 - Uitwerking tentamen.pdf',note:'11 april 2022; getoetst naast het aangeleverde tentamen. Onder meer Rosen.'},
E22O:{file:'2022-10 CAFA2 - Uitwerking tentamen.pdf',note:'6 oktober 2022; getoetst naast het aangeleverde tentamen. Onder meer Rast Holding en Molina.'},
E23A:{file:'20230411 Uitwerking tentamen CAFA2.pdf',note:'11 april 2023; getoetst naast het aangeleverde tentamen. Onder meer Moneglia, Rapallo en Bruggeman.'},
E23O:{file:'20231009 Uitwerking tentamen CAFA2.pdf',note:'9 oktober 2023; getoetst naast het aangeleverde tentamen. Onder meer Voorn, Patti en Gluton.'},
E24A:{file:'20240422 Uitwerking tentamen CAFA2.pdf',note:'22 april 2024; getoetst naast het aangeleverde tentamen. Onder meer Monopoli en Galster.'},
E24S:{file:'20240930 Uitwerking tentamen CAFA2.pdf',note:'30 september 2024; getoetst naast het aangeleverde tentamen. Onder meer Mulini, Bornholm en Hoza.'},
E25A:{file:'20250417 Uitwerking tentamen CAFA2.pdf',note:'17 april 2025; getoetst naast het aangeleverde tentamen. Onder meer Montone, Hoek, Kisjes en Orvelde.'},
E25S:{file:'20250924 Uitwerking tentamen CAFA2 (na normering).pdf',note:'24 september 2025, versie na normering; getoetst naast het aangeleverde tentamen. Onder meer Monserrato, Dole, Oldemarcke en SchierGlas.'},
U:{file:'Door de gebruiker aangeleverde screenshots van de voorraadtabel',note:'Leeg zeskoloms sjabloon en Moderna naar ChargeIT met 60%-interne correctie. De cijfers uit het screenshot zijn gebruikt; aanvullende belastingaannamen bij oefenvarianten worden afzonderlijk vermeld.'}
};
export const coverage=[
['Kapitaalbelangen: deelneming, belegging, dochter en groep','kwalificatie,dochter,consolidatieplicht','S1 §2–4 en §11','Juridische toets plus schema; oefenmodule kap.'],
['Stem- en winstrechten; flex-bv','flex-aandelen','S1 §3 en §5; Finken/Patti/Bosa','Afzonderlijke stem-, dividend- en vermogensberekening.'],
['NVW, zichtbaar intrinsieke waarde, verkrijgingsprijs en actuele waarde','waardering,stelselwijziging','S1 §5 en §8–9','Beslisroute, vergelijking, waarderingsboekingen.'],
['Fair value, goodwill en aandelenruil','fair-value,goodwill,aandelenruil','S1 §5–6','Aankoopstaat, emissie, goodwill- en afschrijvingsboekingen.'],
['Resultaat deelneming, dividend en vermogensaansluiting','resultaat-deelneming,dividend','S1 §5 en §8','Resultaatbrug, mutatieboekingen en eindvermogenscontrole.'],
['Wettelijke reserve deelneming','wettelijke-reserve','S1 §7; art. 2:389 lid 6','Voorwaarden, cumulatief/per deelneming, boeking binnen eigen vermogen.'],
['Direct en middellijk eigen aandelen','eigen-aandelen','S1 §10','Boekingen, omvangvarianten en bronnummeringsverschil.'],
['Consolidatieplicht, kring en vrijstellingen','consolidatieplicht','S1 §11','Afzonderlijke toets art. 2:406–409.'],
['Valutasoorten en functionele valuta','valuta,functionele-valuta,valuta-methoden','S2 §2–4','Factoren RJ 122.106–109 en methodekeuze.'],
['Tijdstipmethode: vaste activa, afschrijving en voorraad','tijdstipmethode,valuta-voorraad','S2 §4.1','Actieflagen, FIFO-casustabel en kostprijscontrole.'],
['Lagere voorraadwaarde en boekresultaat','valuta-afwaardering,tijdstipmethode','S2 §4.1','Oude/nieuwe euroboekwaarde en afwaarderingsjournaal.'],
['Monetaire positie en omrekenresultaat','monetaire-positie','S2 §4.1 en voorbeelden','Complete verloopstaat, tekenafspraak en dubbeltellingscontrole.'],
['Slotkoersmethode en reserve','slotkoersmethode,omrekenreserve,valuta-deelneming','S2 §4.2','Vermogensbrug, ontleding en moederboekingen.'],
['Consolidatieproces en onderlinge relaties','proces,onderlinge-posten','S3 §2','Werklaagonderscheid, zes relaties en eliminatievoorbeelden.'],
['Integrale consolidatie NVW, 100% en niet-100%','consolidatie-nvw','S3 §3.1 en §4.1','Basisbalans- en W&V-eliminatie, met en zonder derden.'],
['Integrale consolidatie HK, 100% en niet-100%','consolidatie-hk','S3 §5.1 en §6.1','Verkrijgingsbasis, eindderden, goodwill, dividend en resultaat.'],
['Richtingen en NVW tegenover HK','streams,ic-boekingsmethoden','S3 §4–6 en §8.1; college-Excel','Vergelijkingsmatrix en expliciete verschillende tussenboekingen.'],
['Downstream NVW toename/afname','voorraadtabel,downstream-nvw','S3 §4.2.1 en §4.3.1','Zeskolomstabel, interne journaalposten, balans, W&V en controle.'],
['Upstream NVW toename/afname','upstream-nvw','S3 §4.2.2 en §4.3.2','Volledige boekingsset en aansluiting met basiseliminatie.'],
['Downstream HK toename/afname','downstream-hk','S3 §6.2.1 en §6.3.1','Geen interne correctie, volledige meerderheidscorrectie.'],
['Upstream HK toename/afname','upstream-hk','S3 §6.2.2 en §6.3.2','Meerderheid/derden, beginwinst, eindwinst en resultaat.'],
['Sidestream niet-afnemend en afnemend belang','sidestream,sidestream-nab,sidestream-ab','S3 §8.1','Vier NVW-varianten; HK-NAB benoemd; ontbrekende HK-AB-bron niet ingevuld.'],
['Interne materiële vaste activa','mva','S3 §8.2','Boekwinst, uitstel, extra afschrijving, restant en derden.'],
['Proportionele consolidatie en joint venture','proportioneel','S3 §7; art. 2:409','Opnameomvang, geen derden, interne relaties en vergelijking integraal.'],
['Afsluitende resultaat- en voorraadcontrole','resultaataansluiting,tentamen','S3 en aangeleverde tentamenuitwerkingen','Meerdere goederenstromen, moederresultaat en definitief aandeel derden.']
];
