import {lesson as L,table as T,journal as J,example as E,note as N,flow as F} from './helpers.mjs';
import {functionalCurrencyHtml} from '../study/functional-currency.mjs';
export default [
L('valuta','val','Lokale, functionele en presentatievaluta','Zet bij iedere valutacasus eerst drie labels. Pas daarna zijn koerskeuze en verwerking van het omrekeningsverschil zinvol.',
T(['Valuta','Betekenis','Voorbeeld'],[
['Lokale valuta','Valuta van het land waar de onderneming is gevestigd.','Een Zweedse vennootschap heeft lokaal de SEK.'],
['Functionele valuta','Valuta van de economische omgeving waarin de onderneming hoofdzakelijk geldmiddelen ontvangt en uitgeeft.','Een Zweedse vennootschap kan onder de gegeven omstandigheden een andere functionele valuta hebben dan SEK.'],
['Presentatievaluta','Valuta waarin de jaarrekening wordt weergegeven.','De Nederlandse moeder presenteert in euro’s.'],
['Vreemde valuta','Iedere valuta anders dan de functionele valuta van de betrokken rechtspersoon.','Bepaal dit begrip dus per onderneming, niet alleen vanuit de Nederlandse moeder.']])+
'<p>Omrekening is in CAFA2 nodig om de nettovermogenswaarde, het resultaat uit deelneming en de geconsolideerde jaarrekening te bepalen. Waar nodig worden de buitenlandse jaarstukken eerst aangepast aan de grondslagen van de moeder en de bij verwerving relevante reële waarden. Artikel 2:384 lid 5 BW verlangt toelichting op de omrekeningsgrondslagen en koersverschillen; de nadere methodiek wordt in de syllabus aan RJ 122 ontleend.</p>'+
N('Koersnotatie eerst lezen','In de voorbeelden is de koers doorgaans de europrijs van één eenheid vreemde valuta: vreemde-valutabedrag maal koers geeft euro’s. Is een koers andersom gegeven, dan moet de berekeningsrichting worden aangepast. Gebruik nooit automatisch vermenigvuldiging zonder de notatie te lezen.'),
['S2|§1–2, p. 4; art. 2:384 lid 5 BW en RJ 122','C3|dia 35–37']),
L('functionele-valuta','val','De functionele valuta onderbouwen','Geef bij een motiveringsvraag niet alleen een muntnaam. Koppel de concrete casusfeiten aan de primaire en aanvullende factoren.',
functionalCurrencyHtml,
['S2|§3, p. 5–6; RJ 122.106–109','A2B|Boccalupo, vraag 2, p. 4','E24A|Galster, vraag 9, p. 6']),
L('valuta-methoden','val','Tijdstipmethode tegenover slotkoersmethode','De methode volgt uit de functionele valuta en de omrekening die nodig is. De syllabus behandelt twee hoofdsituaties voor de buitenlandse deelneming en haar moeder.',
T(['Onderdeel','Tijdstipmethode','Slotkoersmethode'],[
['Situatie in de syllabus','Functionele valuta buitenlandse deelneming gelijk aan die van de moeder; de lokale boekhouding wordt daarnaar omgerekend.','Functionele valuta buitenlandse deelneming wijkt af; omrekening naar de presentatie bij de moeder.'],
['Monetaire activa en verplichtingen','Slotkoers.','Slotkoers.'],
['Niet-monetaire activa tegen historische kosten','Relevante historische koers per actief- of voorraadlaag.','Slotkoers op de eindbalans.'],
['Afschrijving en kostprijs historische activa','Koers van de onderliggende historische laag.','Transactiekoers of passende gemiddelde koers zoals in de casus.'],
['Overige resultaatposten','Transactiekoers; gebruik een opgegeven gemiddelde alleen waar passend.','Transactiekoers of passende gemiddelde volgens de casus.'],
['Omrekeningsverschil','In het resultaat; let op een koersdeel binnen een afwaarderingspost.','Rechtstreeks in het eigen vermogen als reserve omrekeningsverschillen.']])+
N('De methode niet gedurende de berekening wisselen','Een machine tegen historische koers waarderen en daarna het totale omrekenverschil zonder nadere grond in de reserve opnemen, mengt de twee methoden. Noteer boven je uitwerking de gekozen methode en geef per post de gebruikte koers aan.'),
['S2|§4–4.2, p. 7–9; RJ 122 zoals behandeld in de syllabus','A2|Wijo, p. 4–8; Corona, p. 10–12']),
L('tijdstipmethode','val','Tijdstipmethode per balans- en resultaatpost','Monetaire posten volgen de slotkoers. Historisch gewaardeerde niet-monetaire posten houden hun relevante historische koers.',
T(['Post','Koers','Aandachtspunt'],[
['Debiteuren, liquide middelen, voorzieningen en schulden','Slotkoers volgens de indeling in deze syllabus.','Neem alleen het nog openstaande eindbedrag op.'],
['Gebouwen en machines tegen historische kosten','Koers bij aanschaf; bij al vóór verwerving aanwezige activa de in de syllabus aangewezen koers op verwerving van de deelneming door de moeder.','Volg latere investeringen als afzonderlijke lagen.'],
['Voorraad tegen historische kosten','Koers van de resterende inkooplaag.','Bepaal eerst de afgiftevolgorde, bijvoorbeeld FIFO.'],
['Afschrijving en kostprijs','De koers die hoort bij het afgeschreven of verbruikte historische actief.','Niet automatisch de gemiddelde jaarkoers.'],
['Niet-monetaire actuele waarde','De volgens de waarderingssituatie toepasselijke actuele koers.','De syllabus behandelt de samenhang met herwaardering; houd actuele waarde en historische kosten gescheiden.'],
['Afwaardering naar lagere waarde','Lagere waarde omgerekend op het afwaarderingsmoment.','Het verschil met de historische euroboekwaarde hoort bij de afwaardering.']])+
E('Gebouw met een investering op 1 juli',T(['Laag','Berekening in vreemde valuta','Koers','Euroboekwaarde'],[['Bestaand gebouw','900.000 − 30.000','0,910',791700],['Investering 1 juli','240.000 − 20.000 × 6/12','0,920',211600],['Totaal','','',1003300]])+
'<p>De jaarafschrijving in euro’s is € 30.000 × 0,910 + € 10.000 × 0,920 = € 36.500. Een controle is dat eurobeginwaarde plus euro-investering minus euroafschrijving op dezelfde eindboekwaarde aansluit.</p>')+
N('Verwervingsmoment moeder','Wanneer een machine vóór de aankoop van de deelneming is aangeschaft, gebruik je voor de in deze syllabus behandelde deelnemingsomrekening niet blind de oudste aanschafkoers. Het aankoopmoment van de deelneming bepaalt dan de relevante historische basis voor de moeder.'),
['S2|§4.1, p. 8–9','E25S|gebouwen, vraag 9a, p. 6','E24A|vraag 10a, p. 6']),
L('valuta-voorraad','val','Voorraad en kostprijs: eerst de inkooplagen','Een voorraadberekening moet zelfstandig een partijentabel bevatten. Zo worden aantallen, prijzen en koersen niet uit eerdere vragen verondersteld.',
F(['Zet beginvoorraad, inkopen en verkopen chronologisch in een tabel.','Werk verkopen volgens de voorgeschreven afgiftevolgorde weg.','Bepaal de resterende aantallen per inkooplaag.','Reken voorraad en verbruik om tegen de historische koers van die laag.'])+
E('FIFO: complete casus en eindvoorraad',T(['Moment','Beweging','Aantal','Inkoopprijs USD','Historische koers'],[['Begin','Beginvoorraad',4000,40,'0,910'],['Maart','Inkoop',3000,42,'0,920'],['Mei','Verkoop',-5000,'',''],['September','Inkoop',2000,44,'0,930'],['November','Verkoop',-1000,'','']])+
'<p>De eerste verkoop verbruikt 4.000 stuks beginvoorraad en 1.000 stuks uit maart. De tweede verkoop verbruikt nog 1.000 stuks uit maart. Eindvoorraad: 1.000 maartstuks en 2.000 septemberstuks.</p>'+
T(['Resterende laag','Aantal','USD per stuk','Koers','Waarde (€)'],[['Maart',1000,42,'0,920',38640],['September',2000,44,'0,930',81840],['Eindvoorraad',3000,'','',120480]])+
'<p>Controle aantallen: 4.000 + 3.000 + 2.000 − 5.000 − 1.000 = 3.000. De kostprijs van de verkopen wordt met de verbruikte lagen berekend; de omzet gebruikt juist de verkoopprijzen en koersen op verkoopmomenten.</p>')+
N('Bruto voorraad versus lagere waarde','Bereken de historische partijwaarde eerst. Controleer daarna of een deel naar lagere waarde moet worden afgewaardeerd. De koersbehandeling van dat deel wijkt af en moet afzonderlijk zichtbaar zijn.'),
['S2|§4.1, p. 8–9 en voorbeeld §4.3','A2|Wijo, p. 4–6; Corona, p. 10–11','E25S|vraag 9b, p. 6','E24A|vraag 10b, p. 6']),
L('valuta-afwaardering','val','Afwaardering van voorraad inclusief het koerseffect','De afwaarderingslast is het verschil tussen twee euroboekwaarden. Reken niet alleen het buitenlandse prijsverschil tegen één koers om.',
T(['Berekening','Koersbasis'],[['Oude euroboekwaarde','Aantal × historische inkoopprijs × historische koers.'],['Nieuwe lagere euroboekwaarde','Aantal × lagere waarde per stuk × koers op afwaarderingsmoment.'],['Afwaarderingslast','Oude euroboekwaarde minus nieuwe lagere euroboekwaarde.'],['Niet-afgewaardeerd deel','Blijft op de eigen historische prijs en koers staan.']])+
E('2.000 stuks van USD 40 naar USD 30','<p>Historische koers: € 0,920 per USD. Koers bij afwaardering: € 0,935 per USD. Oude boekwaarde: 2.000 × USD 40 × 0,920 = € 73.600. Nieuwe boekwaarde: 2.000 × USD 30 × 0,935 = € 56.100. Afwaarderingslast: € 17.500.</p>'+
J('Afwaardering in euro’s',[['4.. Afwaarderingskosten voorraad',17500,''],['7.. Aan Voorraad','',17500]])+
'<p>Alleen USD 20.000 prijsdaling × 0,920 = € 18.400 berekenen is onvolledig: de resterende waarde heeft ook een andere koers. Het koersdeel zit volgens de syllabus in dezelfde afwaarderingslast.</p>')+
N('Geen dubbele koerscorrectie','Voorraad is in deze berekening niet monetair. Neem het koersdeel van deze afwaardering daarom niet nogmaals op als verlies uit de monetaire positie. Splits bij gedeeltelijke afwaardering de betrokken partij eerst in een onaangetast en afgewaardeerd deel.'),
['S2|§4.1, p. 8','A2B|Boccalupo, p. 5–6','E25S|vraag 9b–10, p. 6–7','E24A|vraag 11c, p. 7']),
L('monetaire-positie','val','Omrekeningsverschil via de monetaire positie','Een sluitende monetaire verloopstaat verklaart het koersresultaat bij de tijdstipmethode. Houd zowel vreemde valuta als euro’s bij.',
F(['Bereken monetaire activa minus monetaire verplichtingen op begindatum.','Neem uitsluitend netto monetaire mutaties op tegen hun transactiekoersen.','Sluit de buitenlandse eindpositie aan op de balans.','Vergelijk de theoretische euro-eindpositie met de werkelijke positie tegen slotkoers.'])+
T(['Gebeurtenis','Netto effect op de monetaire positie'],[['Contante verkoop','Toename monetaire middelen.'],['Contante inkoop of betaling bedrijfskosten','Afname monetaire middelen.'],['Aankoop machine contant','Afname: geld verlaat de monetaire positie en wordt een niet-monetair actief.'],['Ontvangst op debiteur','Geen netto mutatie: vordering wordt bank.'],['Aflossing lening','Geen netto mutatie: bank én schuld nemen af.'],['Afschrijving machine','Geen monetaire mutatie.'],['Afboeking ongedekte debiteur','Vermindering van de monetaire vordering; verwerk volgens de casus.']])+
E('Volledige monetaire aansluiting',T(['Regel','USD','Koers','Theoretisch €'],[['Beginpositie',-300000,'0,910',-273000],['Ontvangsten verkopen',600000,'0,920',552000],['Betaalde inkopen',-400000,'0,915',-366000],['Betaalde kosten',-50000,'0,918',-45900],['Theoretische eindpositie',-150000,'',-132900],['Werkelijke eindpositie',-150000,'0,930',-139500]])+
'<p>Hier betekent koersresultaat: werkelijke europositie minus theoretische europositie. Dat is −€ 139.500 − (−€ 132.900) = −€ 6.600, dus een verlies. De buitenlandse kolom sluit al vóór deze koerscorrectie.</p>')+
N('Tekenafspraak expliciet maken','Een netto schuld wordt bij een hogere europrijs van de vreemde valuta zwaarder. Dat past bij een koersverlies. Bronuitwerkingen kunnen het verlies als positief saldobedrag tonen; vergelijk daarom de economische richting, niet alleen het geschreven plus- of minteken.'),
['S2|§4.1 en voorbeeld, p. 9 en 15','A2|Wijo, p. 6; Corona, p. 11','A2B|M&D, p. 40–41','E25A|vraag 11, p. 8']),
L('slotkoersmethode','val','Slotkoersmethode: balans en resultaat apart omrekenen','Activa en verplichtingen worden tegen slotkoers opgenomen. Het resultaat volgt de passende transactiekoersen of de in de casus toegestane gemiddelde koers.',
T(['Onderdeel','Werkwijze'],[['Activa en verplichtingen eindbalans','Omrekenen tegen de koers op einddatum, ook gebouwen en voorraad.'],['Geplaatst kapitaal en bestaande reserves','Volg de historische en overgenomen eurobedragen in de vermogensaansluiting.'],['Resultaat boekjaar','Reken de resultaatposten om met hun toepasselijke koersen; gebruik de opgegeven gemiddelde waar die volgens de casus past.'],['Dividend','Omrekenen tegen de koers bij het uitkeringsrecht of de in de casus gegeven uitkering.'],['Sluitverschil','Verwerken in de reserve omrekeningsverschillen, niet in de winst-en-verliesrekening.']])+
E('Eenzelfde machine geeft een andere balanswaarde','<p>De machine heeft na afschrijving een boekwaarde van USD 420.000. Bij slotkoers € 0,914 is de eindbalanswaarde € 383.880. Dat is niet de € 382.200 die zou volgen uit de historische koers € 0,910 bij de tijdstipmethode. Welke uitkomst juist is, hangt dus eerst af van de methode.</p>')+
N('Geen monetaire-positieanalyse voor deze reserve','Bij de slotkoersmethode verklaar je het reserveverschil via het eigen vermogen, resultaat en dividend. Neem niet de monetaire verloopstaat van de tijdstipmethode als vervangende berekening over.'),
['S2|§4.2, p. 9 en voorbeeld p. 16–17','A2|Wijo, p. 7–8; Corona, p. 12','E25A|vraag 13–14, p. 9']),
L('omrekenreserve','val','Reserve omrekeningsverschillen berekenen','Gebruik twee controles: een volledige vermogensbrug en een ontleding van het koersverschil op beginvermogen, winst en dividend.',
E('Beginvermogen 1.000.000, winst 120.000 en dividend 40.000','<p>De relevante koersen zijn begin € 0,910, resultaat € 0,920, dividend € 0,925 en slot € 0,930. Het eindvermogen in vreemde valuta is 1.080.000.</p>'+
T(['Vermogensbrug','Bedrag (€)'],[['Eindvermogen: 1.080.000 × 0,930',1004400],['Af: beginvermogen 1.000.000 × 0,910',-910000],['Af: resultaat 120.000 × 0,920',-110400],['Bij: dividend 40.000 × 0,925',37000],['Positief omrekeningsverschil',21000]])+
T(['Ontleding','Berekening','Bedrag (€)'],[['Beginvermogen','1.000.000 × (0,930 − 0,910)',20000],['Winst','120.000 × (0,930 − 0,920)',1200],['Dividend','−40.000 × (0,930 − 0,925)',-200],['Totaal','',21000]]))+
'<p>De reserve ontstaat door dezelfde vermogensbestanddelen tegen verschillende passende koersen te volgen. Bij een negatief verschil draait de richting van de reserveboeking om; dat hoeft niet te betekenen dat de buitenlandse eenheid een verlies heeft geleden.</p>'+
N('Resultaat blijft resultaat','De winst tegen de resultaatkoers en de reserve-mutatie zijn afzonderlijke bedragen. Voeg het koersverschil niet alsnog aan resultaat deelneming toe wanneer de slotkoersmethode wordt toegepast.'),
['S2|§4.2 en voorbeeld, p. 9 en 16–17','A2|Wijo, p. 7–8','E24S|vraag 11b, p. 8','E25A|vraag 13–14, p. 9']),
L('valuta-deelneming','val','Boekingen bij de moeder en afsluitende controle','Pas het deelnemingspercentage pas toe nadat resultaat en vermogen correct in euro’s zijn bepaald. Houd dividend, resultaat en rechtstreekse koersmutaties apart.',
T(['Gebeurtenis','Boeking bij NVW'],[['Positief aangepast euroresultaat','Deelneming aan resultaat deelneming, voor het moederdeel.'],['Tijdstipmethode: koersverlies','Eerst in het euroresultaat verwerken; niet ook als afzonderlijke omrekenreserve boeken.'],['Slotkoersmethode: positieve omrekenreserve','Deelneming aan reserve omrekeningsverschillen, voor het moederdeel.'],['Slotkoersmethode: negatieve omrekenreserve','Reserve omrekeningsverschillen aan deelneming.'],['Dividend','Bank of dividendvordering aan deelneming, tegen de toepasselijke uitkeringskoers.']])+
E('Boekingen bij 80% in het voorbeeld van de omrekenreserve',J('Resultaat en positief omrekeningsverschil',[['0.. Deelneming',105120,''],['9.. Aan Resultaat deelneming','',88320],['0.. Aan Reserve omrekeningsverschillen','',16800]])+
J('Dividend apart',[['1.. Bank',29600,''],['0.. Aan Deelneming','',29600]])+
'<p>De beginwaarde is 80% × € 910.000 = € 728.000. Eindwaarde: € 728.000 + € 105.120 − € 29.600 = € 803.520. Dit is ook 80% × € 1.004.400, het omgerekende eindvermogen. Is het dividend al geboekt, dan wordt alleen de eerste boeking nog gemaakt.</p>')+
N('Eindcontrole voor iedere valutacasus','Sluiten de balans, de winst-en-verliesrekening en de omrekening op elkaar aan? Zijn waarderingsverschillen naar moedergrondslagen verwerkt? Is het onderscheid tussen tijdstipmethode en slotkoersmethode consequent volgehouden? Staat bij elke koers de datum of functie?'),
['S1|§5.1.2, p. 16–17; art. 2:389 lid 2 BW','S2|§4, p. 7–17','A2|Wijo, vraag 3 en 5, p. 6–8','E25A|Hoek, p. 8–9'])
];
